import {chromium,firefox,webkit,expect} from '@playwright/test';
import assert from 'node:assert/strict';import fs from 'node:fs/promises';
const out=process.env.SB_EMBER_UI_OUT??'.local-validation/v07/browser';await fs.mkdir(out,{recursive:true});
const report={kind:'ASSIGNED_STATE_REAL_UI_NOT_NATURAL_CAMPAIGN',checks:[],captures:[],browsers:[],errors:[],startedAt:new Date().toISOString()};
for(const engine of (process.env.SB_EMBER_ENGINE?[process.env.SB_EMBER_ENGINE]:['chromium','firefox','webkit'])){
 const browser=await ({chromium,firefox,webkit}[engine]).launch({headless:true}),context=await browser.newContext({viewport:{width:1366,height:768},recordVideo:engine==='chromium'?{dir:out}:undefined}),page=await context.newPage();page.setDefaultTimeout(20000);
 const errors=[];page.on('pageerror',e=>errors.push(e.message));page.on('console',m=>{if(m.type()==='error')errors.push(m.text());});
 report.browsers.push({engine,version:browser.version()});
 const check=id=>{report.checks.push({id,engine,status:'PASS'});console.log('PASS',engine,id);};
 const capture=async id=>{const file=`ASSIGNED-${engine}-${id}.png`;await page.screenshot({path:out+'/'+file,fullPage:true});report.captures.push(file);};
 try{
 await page.goto('http://127.0.0.1:5173/',{timeout:60000});await page.locator('#start-run').waitFor();
 await page.evaluate(async()=>{
  const [f,{RunController},{renderCombat},{renderIntro,renderStageClear,renderResult},{playAttack,createDOMPresentation},{presentOperation},overlays,{LocalStore},{registryForVersion},{snapshotFromText},{cardKind}]=await Promise.all([import('/tests/helpers/ember-state.js'),import('/src/game/runController.js'),import('/src/ui/combat.js'),import('/src/ui/progression.js'),import('/src/engine/presentation.js'),import('/src/ui/operationPresentation.js'),import('/src/ui/overlays.js'),import('/src/services/localStore.js'),import('/src/data/language/index.js'),import('/src/engine/grammar/index.js'),import('/src/data/cardCatalog.js')]);
  const store=new LocalStore({registry:registryForVersion('0.7.0')});await store.init();
  window.qa={f,store,root:document.querySelector('#app'),settings:{speed:2,effectsOff:false},events:[],async reset(round=0){this.c=f.assignedEmber({round});this.profile=this.c.getProfile();await store.saveProfile(this.profile);this.events=[];this.show();},show(){this.view?.cleanup();const s=this.c.getState();if(s.status==='BATTLE')this.view=renderCombat(this.root,s,{command:c=>this.command(c),openOverlay:k=>this.overlay(k)});else if(s.status==='CONTENT_COMPLETE')renderResult(this.root,s,{});else if(s.status==='STAGE_INTRO')renderIntro(this.root,s,{onStart:()=>this.command({type:'ENTER_STAGE'})});else this.root.textContent=s.status;},overlay(k){if(k==='saves')return overlays.openSaves({store,profile:this.profile,state:this.c.getState(),onLoad:s=>{this.c=new RunController({initialState:s,profile:this.profile});this.show();}});if(k==='records')return overlays.openRecords(this.c.getProfile(),this.c.getState());return overlays.openDeck(this.c.getState(),k);},async command(command){const before=this.c.getState(),r=this.c.dispatch(command);this.last=r;if(!r.ok)return r;if(r.noRender)return r;
   if(r.operationEffect){this.effect=r.operationEffect;await presentOperation(r.operationEffect,{sourceElement:[...this.root.querySelectorAll('[data-card-id]')].find(n=>n.dataset.cardId===r.operationEffect.sourceCardId),showAfter:()=>{this.show();return this.view.element;}});f.checked(this.c,{type:'FINISH_OPERATION',effectId:r.operationEffect.effectId});}
   if(r.resolution){this.resolution=r.resolution;this.view?.cleanup();this.view=renderCombat(this.root,before,{locked:true});const adapter=createDOMPresentation(this.root),impact=adapter.impact,highlight=adapter.highlight;this.roleFrames=[];adapter.highlight=(...args)=>{highlight(...args);const roles=[...this.root.querySelectorAll('[data-presentation-role]')].filter(n=>n.getBoundingClientRect().width>0&&getComputedStyle(n).visibility!=='hidden').map(n=>({cardId:n.closest('[data-card-id]')?.dataset.cardId,role:n.textContent}));if(roles.length)this.roleFrames.push(roles);};adapter.impact=(...args)=>{impact(...args);this.events.push({kind:'IMPACT',hp:this.root.querySelector('[data-presentation=hp]').textContent,scale:this.root.querySelector('[data-presentation=ember-scale]')?.dataset.active});};this.abort=new AbortController();this.presenting=true;await playAttack(r.resolution,adapter,{...this.settings,signal:this.abort.signal});this.presenting=false;f.checked(this.c,{type:'FINISH_PRESENTATION',attackId:r.resolution.attackId});}
   this.show();return r;},words(text,round=0){this.c=f.assignedEmber({round});const s=this.c.getState(),tokens=snapshotFromText(text,{registry:registryForVersion(s.version)}).orderedTokens,ids=s.activeCardIds.filter(id=>cardKind(s.cardInstances[id],s.version)==='WORD').slice(0,tokens.length);tokens.forEach((t,i)=>s.cardInstances[ids[i]].cardDefId=t.cardDefId);this.c._state=s;f.assignPiles(this.c,{hand:ids});this.tokens=tokens.map((t,i)=>({id:ids[i],formId:t.selectionId}));this.events=[];this.show();return this.tokens;},op(kind,level=0){this.c=f.assignedEmber();const source=f.grantOperation(this.c,kind,level),s=this.c.getState(),dust=s.combat.temporaryCardIds;f.assignPiles(this.c,{hand:[source],draw:kind==='recycle'?s.activeCardIds.filter(id=>id!==source):[...dust,...s.activeCardIds.filter(id=>id!==source)],discard:kind==='recycle'?dust:[]});this.source=source;this.show();},capacity(hand){this.c=f.assignedEmber({round:4,opening:3});const s=this.c.getState();while(s.activeCardIds.length<16+hand){const id='capacity.'+s.activeCardIds.length;s.activeCardIds.push(id);s.cardInstances[id]={instanceId:id,cardDefId:'card.book',polishLevel:0,specialEffectId:null};}const board=s.activeCardIds.slice(0,16),ids=[...s.combat.temporaryCardIds,...s.activeCardIds.slice(16)].slice(0,hand);s.combat.handIds=ids;s.combat.sentenceSlots=board.map(cardInstanceId=>({cardInstanceId,selection:null}));s.combat.drawIds=[...s.activeCardIds,...s.combat.temporaryCardIds].filter(id=>!ids.includes(id)&&!board.includes(id));s.runes.orderedInstanceIds=['r1','r2','r3','r4'];s.runes.instances=Object.fromEntries(['rune.perfectSentence','rune.short','rune.longSentence','rune.discards'].map((runeId,i)=>['r'+(i+1),{instanceId:'r'+(i+1),runeId,level:1}]));this.c._state=s;this.show();}};
  await qa.reset();
 });
 for(const round of [0,4]){await page.evaluate(r=>qa.reset(r),round);assert.ok((await page.locator('.dust-counter').innerText()).includes(round?'5 / 5':'2 / 2'));await capture(round?'boss-opening':'normal-opening');check(`SUPPLY_${round?5:2}_THEME`);}
 await page.evaluate(()=>{const s=qa.c.getState();qa.f.assignPiles(qa.c,{hand:[s.combat.temporaryCardIds[0],...s.activeCardIds.slice(0,4)]});qa.show();});
 const dust=page.locator('.hand-cards .obstacle-card').first(),id=await dust.getAttribute('data-card-id');
 assert.equal(await dust.locator('.form-button,.operation-use,.card-value,.pos-label').count(),0);const box=await dust.locator('.card-select').boundingBox();assert.ok(box.width>=44&&box.height>=44);await dust.locator('.card-select').focus();await page.keyboard.press('Space');await expect(dust.locator('.card-select')).toHaveAttribute('aria-pressed','true');await capture('dust-keyboard-selected');check('DUST_KEYBOARD_44PX_NO_FORM_USE_SCORE');
 const before=await page.evaluate(()=>qa.c.getState()),from=await dust.locator('.card-body').boundingBox(),to=await page.locator('.combat-sentence').boundingBox();await page.mouse.move(from.x+from.width/2,from.y+from.height/2);await page.mouse.down();await page.mouse.move(to.x+to.width/2,to.y+to.height/2,{steps:12});await page.mouse.up();assert.deepEqual(await page.evaluate(()=>qa.c.getState()),before);assert.equal(await page.locator('.drag-ghost,.drag-source').count(),0);check('DUST_DRAG_REJECT_NO_POINTER_RESIDUE');
 await page.locator('#discard-selected').click();const exchanged=await page.evaluate(()=>qa.c.getState());assert.ok(exchanged.combat.discardIds.includes(id));assert.equal(exchanged.combat.exchangesRemaining,before.combat.exchangesRemaining-1);assert.equal(exchanged.combat.turnsRemaining,before.combat.turnsRemaining);check('DUST_EXCHANGE_REAL_UI');
 await page.evaluate(()=>{const s=qa.c.getState();qa.f.assignPiles(qa.c,{hand:s.combat.temporaryCardIds});qa.c._state.combat.exchangesRemaining=0;qa.show();});assert.equal(await page.locator('#attack-submit').isDisabled(),true);assert.equal(await page.locator('#discard-selected').isDisabled(),true);await page.getByRole('button',{name:/준비 · 다음 턴/}).click();assert.equal(await page.evaluate(()=>qa.c.getState().combat.turnIndex),2);assert.ok((await page.evaluate(()=>qa.c.getState().combat.handIds.length))>2);check('ONLY_DUST_NO_EXCHANGE_STILL_PREPARES_WITH_REAL_DRAW');
 for(const kind of ['supply','search','nounSearch','verbSearch','adjectiveSearch','connectorSearch','recycle']){
  await page.evaluate(k=>qa.op(k),kind);const old=await page.evaluate(()=>qa.c.getState());if(await page.locator('.operation-use').isDisabled()){check(kind.toUpperCase()+'_NO_TARGET_FREE');continue;}await page.locator('.operation-use').click();
  if(kind==='search'){assert.equal(await page.locator('.operation-target .obstacle-card').count(),0);await capture('word-search-excludes-dust');await page.locator('.operation-target').first().click();}
  await page.waitForFunction(()=>qa.c.getState().combat.operationHistory.length===1&&qa.c.getState().combat.phase==='EDIT');const effect=await page.evaluate(()=>qa.effect);if(['supply','recycle'].includes(kind))assert.ok(effect.drawnCardIds.every(id=>old.combat.temporaryCardIds.includes(id)));else assert.ok(effect.drawnCardIds.every(id=>!old.combat.temporaryCardIds.includes(id)));await capture(kind+'-result');check('REAL_UI_'+kind.toUpperCase());
 }
 await page.evaluate(()=>qa.op('recycle'));await page.locator('.operation-use').click();await page.waitForFunction(()=>qa.c.getState().combat.phase==='EDIT'&&qa.c.getState().combat.operationHistory.length===1);
 await page.getByRole('button',{name:'저장',exact:true}).click();await page.getByRole('button',{name:'슬롯 1 저장',exact:true}).click();await page.locator('dialog [role=status]').filter({hasText:'저장했습니다'}).waitFor();await page.keyboard.press('Escape');const saved=await page.evaluate(()=>qa.c.getState());await page.evaluate(()=>qa.command({type:'PREPARE'}));await page.getByRole('button',{name:'저장',exact:true}).click();await page.getByRole('button',{name:'슬롯 1 불러오기',exact:true}).click();await expect(page.locator('dialog[open]')).toHaveCount(0);assert.deepEqual(await page.evaluate(()=>qa.c.getState()),saved);check('DUST_OPERATION_RECEIPT_INDEXEDDB_EXACT_RESTORE');
 for(const corruption of ['version','manifest']){
  await page.evaluate(async kind=>{const run=qa.c.getState();if(kind==='manifest')run.contentManifest.id='campaign.unknown';qa.badRow={key:qa.profile.playerId+':3',slot:3,playerId:qa.profile.playerId,savedAt:1,version:kind==='version'?'0.8.0':'0.7.0',run};await qa.store._transaction('slots','readwrite',s=>s.put(qa.badRow));},corruption);
  const before=await page.evaluate(()=>qa.c.getState());await page.getByRole('button',{name:'저장',exact:true}).click();await page.getByRole('button',{name:'슬롯 3 불러오기',exact:true}).click();await page.locator('dialog [role=status]').filter({hasText:'완료하지 못했습니다'}).waitFor();assert.deepEqual(await page.evaluate(()=>qa.c.getState()),before);assert.equal(await page.evaluate(async()=>JSON.stringify(await qa.store._transaction('slots','readonly',s=>s.get(qa.badRow.key)))===JSON.stringify(qa.badRow)),true);await page.keyboard.press('Escape');check('REJECT_'+corruption.toUpperCase()+'_WITHOUT_ERASING_INDEXEDDB_SLOT');
 }
 const compose=async text=>{const tokens=await page.evaluate(t=>qa.words(t,4),text);if(text==='The running child is happy.'){await page.evaluate(()=>{const s=qa.c.getState(),id=s.combat.temporaryCardIds[0];s.combat.handIds.push(id);s.combat.drawIds=s.combat.drawIds.filter(x=>x!==id);qa.c._state=s;qa.show();});await page.locator('.hand-cards .obstacle-card .card-select').click();await page.locator('#discard-selected').click();assert.equal(await page.locator('.operation-card').count(),0);}for(const t of tokens){await page.locator(`[data-card-id="${t.id}"] .card-body`).click();await page.locator(`.combat-sentence [data-card-id="${t.id}"] .form-button`).click();await page.locator(`dialog [data-form-id="${t.formId}"],dialog [data-form-aliases~="${t.formId}"]`).click();}};
 for(const text of ['The running child is happy.','The finished homework is easy.','The child reading a book is happy.','The food made today is good.','Food is eaten.','I see him run.','I see him running.','I see the food eaten.','I have made food.','I enjoy eating food.']){
  await compose(text);const oldHp=await page.locator('[data-presentation=hp]').innerText();assert.equal(await page.locator('[data-presentation=score]').isVisible(),false);await page.locator('#attack-submit').click();await page.waitForFunction(()=>qa.presenting===true);assert.equal(await page.locator('[data-presentation=hp]').innerText(),oldHp);assert.equal(await page.locator('[data-presentation=ember-scale]').getAttribute('data-active'),'true');await page.waitForFunction(()=>qa.roleFrames.length>0);await capture('submitted-roles-'+text.replace(/[^a-z]+/gi,'-'));await page.waitForFunction(()=>qa.presenting===false,{},{timeout:45000});const r=await page.evaluate(()=>({resolution:qa.resolution,events:qa.events,roleFrames:qa.roleFrames}));assert.equal(r.resolution.status,'VALID');assert.ok(r.roleFrames.length>0);assert.ok(r.roleFrames.flat().every(x=>r.resolution.sentenceSnapshot.orderedTokens.some(t=>t.cardInstanceId===x.cardId)));assert.equal(r.events.length,1);assert.equal(r.events[0].scale,String(r.resolution.bossStateAfter.active));await capture('grammar-'+text.replace(/[^a-z]+/gi,'-'));check('REAL_FORMS_ENGINE_IMPACT_'+text);if(text==='The running child is happy.')check('NO_OPERATION_DUST_EXCHANGE_THEN_REAL_ATTACK');
 }
 for(const mode of ['effectsOff','reducedMotion','cancel']){
  await page.emulateMedia({reducedMotion:mode==='reducedMotion'?'reduce':'no-preference'});await page.evaluate(m=>{qa.settings={speed:2,effectsOff:m==='effectsOff'};},mode);await compose('I have made food.');await page.locator('#attack-submit').click();await page.waitForFunction(()=>qa.presenting===true);if(mode==='cancel')await page.evaluate(()=>qa.abort.abort());await page.waitForFunction(()=>qa.presenting===false,{},{timeout:45000});const s=await page.evaluate(()=>qa.c.getState());assert.equal(s.combat.enemyState.bossMechanic.active,false);const old=structuredClone(s);await page.evaluate(()=>qa.command({type:'FINISH_PRESENTATION',attackId:qa.resolution.attackId}));assert.deepEqual(await page.evaluate(()=>qa.c.getState()),old);check('PRESENTATION_'+mode.toUpperCase()+'_NO_DOUBLE_COMMIT');
 }
 await page.emulateMedia({reducedMotion:'no-preference'});
 for(const [width,height]of [[1024,768],[1280,800],[1366,768],[1920,1080]])for(const hand of [10,14]){
  await page.setViewportSize({width,height});await page.evaluate(n=>qa.capacity(n),hand);
  const boxes=await page.evaluate(()=>{const b=s=>{const r=document.querySelector(s).getBoundingClientRect();return {top:r.top,bottom:r.bottom,left:r.left,right:r.right};};return {actions:b('.combat-actions'),hand:b('.hand-cards'),board:b('.combat-sentence'),tools:b('.ember-tools'),info:b('.enemy-info'),enemy:b('.enemy-area'),selects:[...document.querySelectorAll('.obstacle-card .card-select')].map(n=>({width:n.getBoundingClientRect().width,height:n.getBoundingClientRect().height}))};});assert.ok(boxes.actions.bottom<=boxes.hand.top,JSON.stringify(boxes));assert.ok(boxes.board.bottom<=boxes.actions.top,JSON.stringify(boxes));assert.ok(boxes.info.right<=boxes.tools.left);assert.ok(boxes.tools.bottom<=boxes.enemy.bottom+1);assert.ok(boxes.selects.every(b=>b.width>=44&&b.height>=44));await capture(`${width}x${height}-hand${hand}`);check(`LAYOUT_${width}x${height}_${hand}_16_4`);
 }
 assert.deepEqual(errors,[]);check('NO_BROWSER_ERRORS');
 }catch(error){report.errors.push({engine,error:error.stack,browserErrors:errors});console.error(engine,error);await capture('FAILURE').catch(()=>{});}
 finally{const video=page.video();await context.close();if(video)await video.saveAs(out+`/ASSIGNED-${engine}-play.webm`);await browser.close();}
}
report.status=report.errors.length?'FAIL':'PASS';report.finishedAt=new Date().toISOString();await fs.writeFile(out+'/report.json',JSON.stringify(report,null,2));if(report.errors.length)process.exitCode=1;console.log(report.status,report.checks.length,'checks',report.captures.length,'captures');
