import {chromium} from '@playwright/test';import assert from 'node:assert/strict';import fs from 'node:fs/promises';import {playGuided} from './helpers/guided-browser.mjs';
const out=process.env.SB_V021_EVIDENCE||'.local-validation/v021/browser';await fs.mkdir(out,{recursive:true});const browser=await chromium.launch({headless:true});const report={kind:'ACTUAL_GUIDED_UI_WITH_SYNTHETIC_VISIBILITY_EVENT',checks:[],captures:[],errors:[],browser:browser.version()};
try{for(const [width,height]of [[1366,768],[1024,768],[1920,1080]]){
 const context=await browser.newContext({viewport:{width,height},reducedMotion:width===1024?'reduce':'no-preference',recordVideo:{dir:out}}),page=await context.newPage();page.setDefaultTimeout(15000);page.on('pageerror',e=>report.errors.push(e.message));
 const capture=async name=>{const f=`${width}-${name}.png`;await page.screenshot({path:out+'/'+f,fullPage:true});report.captures.push(f);};
 await page.goto('http://127.0.0.1:5173/?debug=1');await page.locator('#player-name').fill('0.2.1 브라우저 검증');await page.locator('#start-run').click();await page.locator('#start-battle').click();
 if(width===1024){await page.getByRole('button',{name:'설정',exact:true}).click();await page.getByLabel('음소거',{exact:true}).check();await page.getByLabel('효과 감소',{exact:true}).check();await page.keyboard.press('Escape');}
 if(width===1366){let restarted=false;try{await playGuided(page,{onGate:async n=>{if(n!==26)return;await page.locator('.guided-gate').getByRole('button',{name:'실습 다시 시작',exact:true}).click();await page.locator('dialog[open]').getByRole('button',{name:'다시 시작',exact:true}).click();await page.locator('[data-tutorial-step="1"]').waitFor();const state=await page.evaluate(()=>__SB_DEV__.getState());assert.equal(state.tutorialSession.attempt,2);assert.equal(state.combat.enemyState.hp,77);assert.equal(state.economy.gold,0);assert.equal(state.combat.pendingAttackId,null);restarted=true;throw Error('EXPECTED_RESTART');}});}catch(error){assert.equal(error.message,'EXPECTED_RESTART');}assert.equal(restarted,true);report.checks.push({id:'ACTUAL_GATE_RESTART',status:'PASS'});}
 await playGuided(page,{capture,drag:width===1366,keyboard:width===1024,inspect:async step=>{
  if(step===1&&width===1366){await page.setViewportSize({width:1366,height:600});await page.mouse.wheel(0,70);await page.waitForFunction(()=>scrollY>0);await page.waitForFunction(async()=>{const {targetSelector}=await import('/src/ui/guidedCoach.js'),b=document.querySelector(targetSelector(__SB_DEV__.getState())).getBoundingClientRect(),r=document.querySelector('.guided-spotlight').getBoundingClientRect();return Math.abs(r.top-(b.top-4))<.5;});report.checks.push({id:'ACTUAL_SCROLL_TARGET',status:'PASS'});await page.evaluate(()=>window.scrollTo(0,0));await page.setViewportSize({width:1024,height:768});await page.evaluate(()=>window.dispatchEvent(new Event('orientationchange')));await page.waitForFunction(async()=>{const {targetSelector}=await import('/src/ui/guidedCoach.js'),b=document.querySelector(targetSelector(__SB_DEV__.getState())).getBoundingClientRect(),r=document.querySelector('.guided-spotlight').getBoundingClientRect();return Math.abs(r.left-(b.left-4))<.5&&Math.abs(r.width-b.width-8)<.5;});await page.setViewportSize({width,height});await page.waitForFunction(async()=>{const {targetSelector}=await import('/src/ui/guidedCoach.js'),b=document.querySelector(targetSelector(__SB_DEV__.getState())).getBoundingClientRect(),r=document.querySelector('.guided-spotlight').getBoundingClientRect();return Math.abs(r.width-b.width-8)<.5;});report.checks.push({id:'RESIZE_ORIENTATION_EVENT_TARGET',status:'PASS'});}
  const geometry=await page.evaluate(async()=>{const {targetSelector}=await import('/src/ui/guidedCoach.js');const target=document.querySelector(targetSelector(__SB_DEV__.getState())).getBoundingClientRect(),b=document.querySelector('.guided-coach').getBoundingClientRect();return{overlap:Math.max(0,Math.min(target.right,b.right)-Math.max(target.left,b.left))*Math.max(0,Math.min(target.bottom,b.bottom)-Math.max(target.top,b.top)),x:b.x,y:b.y,right:b.right,bottom:b.bottom};});assert.equal(geometry.overlap,0,`cue ${step} at ${width}`);assert.ok(geometry.x>=0&&geometry.right<=width&&geometry.y>=0&&geometry.bottom<=height);report.checks.push({id:`TARGET_${width}_${step}`,status:'PASS'});
 },onGate:async step=>{if(step!==26||width!==1366)return;const before=await page.evaluate(()=>__SB_DEV__.getState());await page.evaluate(()=>{Object.defineProperty(document,'hidden',{configurable:true,value:true});document.dispatchEvent(new Event('visibilitychange'));});await page.waitForTimeout(300);assert.equal(await page.locator('.guided-gate').getAttribute('data-cue-id'),'T26');assert.deepEqual(await page.evaluate(()=>__SB_DEV__.getState()),before);await page.evaluate(()=>{delete document.hidden;document.dispatchEvent(new Event('visibilitychange'));});report.checks.push({id:'GUIDED_VISIBILITY_EVENT_NO_FINISH',status:'PASS'});}});
 const end=await page.evaluate(()=>__SB_DEV__.getState()),profile=await page.evaluate(()=>__SB_DEV__.getProfile());assert.equal(end.economy.gold,5);assert.equal(end.activeCardIds.length,28);assert.equal(end.stats.attacks,0);assert.equal(profile.guidedTutorialCompletedVersion,'0.2.1');report.checks.push({id:`COMPLETE_${width}`,status:'PASS'});
 const video=page.video();await context.close();await video.saveAs(out+`/tutorial-${width}.webm`);}
 // Heavy impact sample uses a real parser/score resolution in a labelled renderer fixture.
 const fixtureContext=await browser.newContext({viewport:{width:1366,height:768},recordVideo:{dir:out}}),fixture=await fixtureContext.newPage();await fixture.goto('http://127.0.0.1:5173/');await fixture.locator('#start-run').waitFor();
 const heavy=await fixture.evaluate(async()=>{
  const [{RunController},{newProfile},{snapshotFromText,analyzeSentence},{resolveAttack},{renderCombat},{createDOMPresentation,playAttack},{registry}]=await Promise.all([import('/src/game/runController.js'),import('/src/services/localStore.js'),import('/src/engine/grammar/index.js'),import('/src/engine/stage.js'),import('/src/ui/combat.js'),import('/src/engine/presentation.js'),import('/src/data/language/index.js')]);
  const profile=newProfile('Heavy presentation fixture');profile.guidedTutorialCompletedVersion='0.2.1';const c=new RunController({profile});c.dispatch({type:'NEW_RUN'});c.dispatch({type:'START_BATTLE'});const state=c.getState(),snapshot=snapshotFromText('I run');state.combat.sentenceSlots=snapshot.orderedTokens.map(t=>({cardInstanceId:t.cardInstanceId,selection:{formId:t.selectionId}}));state.cardInstances=Object.fromEntries(snapshot.orderedTokens.map(t=>[t.cardInstanceId,{instanceId:t.cardInstanceId,cardDefId:t.cardDefId,polishLevel:0,specialEffectId:null}]));state.combat.handIds=[];state.combat.drawIds=[];state.combat.discardIds=[];state.activeCardIds=Object.keys(state.cardInstances);
  const resolution=resolveAttack({analysis:analyzeSentence(snapshot),sentenceSnapshot:snapshot,cards:Object.values(state.cardInstances).map(c=>({...c,baseScore:10})),equippedRunes:[],enemy:state.combat.enemyState,policyVersion:'0.2.2'});const root=document.querySelector('#app'),view=renderCombat(root,state,{locked:true});view.beginPresentation();const badge=document.createElement('aside');badge.textContent='강한 타격 연출 fixture · 실제 원정 완주 아님';badge.style='position:fixed;top:0;left:0;background:#eddca7;color:#153322;padding:6px;z-index:20';root.append(badge);const calls=[];const adapter=createDOMPresentation(view.element,{hpMax:77,audio:{play:type=>calls.push({type,hp:root.querySelector('[data-presentation=hp]').textContent})}});const outcome=await playAttack(resolution,adapter,{speed:1});return{outcome,power:resolution.finalPower,tier:view.element.dataset.impactTier,calls};
 });assert.equal(heavy.outcome.status,'FINISHED');assert.equal(heavy.tier,'HEAVY');assert.ok(heavy.calls.some(x=>x.type==='impactLow'));report.checks.push({id:'HEAVY_ENGINE_PRESENTATION_FIXTURE',status:'PASS',detail:heavy});const heavyVideo=fixture.video();await fixtureContext.close();await heavyVideo.saveAs(out+'/heavy-fixture.webm');
 assert.deepEqual(report.errors,[]);report.status='PASS';console.log(JSON.stringify({status:'PASS',checks:report.checks.length,captures:report.captures.length}));
}finally{await fs.writeFile(out+'/report.json',JSON.stringify(report,null,2));await browser.close();}
