/** Module-level real browser verification. Production integrated evidence is recorded separately. */
import {chromium} from '@playwright/test';
import{createServer}from'node:http';import{readFile,mkdir,writeFile}from'node:fs/promises';import{resolve}from'node:path';import assert from'node:assert/strict';
const root=resolve(import.meta.dirname,'..');
await mkdir(resolve(root,'docs/evidence'),{recursive:true});
const server=createServer(async(req,res)=>{try{let p=req.url.split('?')[0];if(p==='/'){res.setHeader('Content-Type','text/html');res.end('<html lang="ko"><meta charset="utf-8"><link rel="stylesheet" href="/src/ui/styles.css"><body><main id="app">OVERLAY BROWSER TEST</main></body></html>');return;}if(!p.startsWith('/src/')||p.includes('..'))throw Error();res.setHeader('Content-Type',p.endsWith('.css')?'text/css':'text/javascript');res.end(await readFile(resolve(root,'.'+p)));}catch{res.statusCode=404;res.end();}});
await new Promise(r=>server.listen(0,'127.0.0.1',r));const browser=await chromium.launch({headless:true,args:['--no-sandbox']});
try{const page=await browser.newPage({viewport:{width:1024,height:768}});const errors=[];page.on('pageerror',e=>errors.push(e.message));await page.goto(`http://127.0.0.1:${server.address().port}/`);
await page.evaluate(async()=>{window.o=await import('/src/ui/overlays.js');const{RunController}=await import('/src/game/runController.js');const{LocalStore}=await import('/src/services/localStore.js');const{registry}=await import('/src/data/language/index.js');window.store=await new LocalStore({registry}).init();window.profile=await store.createProfile('QA 여행자');window.controller=new RunController({profile});let r=controller.dispatch({type:'NEW_RUN',config:{seed:'overlay-test'}});if(!r.ok)throw Error(r.message);r=controller.dispatch({type:'START_BATTLE'});if(!r.ok)throw Error(r.message);window.state=controller.getState();window.before=JSON.stringify(state);o.openDeck(state,'draw');});
assert.match(await page.locator('dialog h2').textContent(),/순서는 공개하지 않음/);assert.equal(await page.locator('dialog .word-card').count(),24);assert.equal(await page.locator('dialog .form-button').count(),0);await page.screenshot({path:resolve(root,'docs/evidence/overlays-draw-readonly.png')});await page.getByRole('button',{name:/닫기/}).click();
await page.evaluate(()=>o.openDictionary(state));assert.ok(await page.locator('.dictionary-entry').count()>=20);await page.getByRole('searchbox').fill('zzzzzz');assert.match(await page.locator('.dictionary-grid').textContent(),/검색 결과가 없습니다/);await page.getByRole('button',{name:/닫기/}).click();
await page.evaluate(()=>o.openSettings(profile.settings,v=>{window.changedSettings=v;}));await page.getByRole('combobox').selectOption('2');await page.getByRole('checkbox',{name:'음소거',exact:true}).check();assert.equal(await page.evaluate(()=>changedSettings.speed),2);assert.equal(await page.evaluate(()=>changedSettings.muted),true);await page.getByRole('button',{name:/닫기/}).click();
await page.evaluate(()=>o.openSaves({store,profile,state,onLoad:run=>{window.loaded=run;}}));await page.getByRole('button',{name:'슬롯 1 저장',exact:true}).click();await page.waitForFunction(()=>document.querySelector('.dialog-body [role=status]').textContent.includes('저장했습니다'));await page.screenshot({path:resolve(root,'docs/evidence/overlays-save-slots.png')});await page.getByRole('button',{name:'슬롯 1 불러오기',exact:true}).click();await page.waitForFunction(()=>window.loaded);assert.equal(await page.evaluate(()=>JSON.stringify(loaded)),await page.evaluate(()=>before));
await page.evaluate(()=>o.openRecords(profile,state));assert.equal(await page.locator('.dictionary-entry').count(),6);await page.getByRole('button',{name:/닫기/}).click();assert.equal(await page.evaluate(()=>JSON.stringify(state)),await page.evaluate(()=>before));
await page.evaluate(()=>o.openSaves({store:{available:true,listSlots:async()=>[{slot:1,empty:true},{slot:2,empty:true},{slot:3,empty:true}],saveRun:async()=>{throw Error('synthetic quota exceeded');}},profile,state,onLoad:()=>{}}));await page.getByRole('button',{name:'슬롯 1 저장',exact:true}).click();await page.waitForFunction(()=>document.querySelector('.dialog-body [role=status]').textContent.includes('synthetic quota'));assert.equal(await page.getByRole('button',{name:'슬롯 1 저장',exact:true}).isEnabled(),true);assert.deepEqual(errors,[]);
const report={status:'PASS',scope:'ISOLATED_REAL_BROWSER_MODULES_NOT_PRODUCTION_BUILD',browser:await browser.version(),viewport:{width:1024,height:768},command:'node tests/overlays-browser.mjs',cases:[
{id:'U10',status:'PASS',evidence:'Draw modal has 24 actual readonly cards, no form controls, hidden-order title; state JSON unchanged.'},
{id:'P02',status:'PASS',evidence:'Real IndexedDB initial checkpoint save/load JSON equality including all piles, turn, selection and RNG.'},
{id:'P03',status:'NOT RUN',evidence:'Frozen reward save/load is not covered by this overlay script.'},
{id:'P07',status:'PARTIAL',evidence:'Injected saveRun rejection leaves visible error and retry available; real transaction rollback is not exercised here.'},
{id:'P10',status:'PASS',evidence:'Dictionary open/search/close leaves full RunState and RNG unchanged.'}
],checks:['draw read-only','dictionary encountered words and search','settings cloned callback','real IndexedDB save/load equal snapshot','six grammar catalog entries without fake records','no state mutation','injected save failure allows retry and memory play']};
await writeFile(resolve(root,'docs/evidence/overlays-browser.json'),JSON.stringify(report,null,2));console.log(JSON.stringify(report,null,2));
}finally{await browser.close();server.close();}
