import {chromium,firefox,webkit,expect} from '@playwright/test';
import assert from 'node:assert/strict';import fs from 'node:fs/promises';
const out=process.env.SB_SNOW_UI_EVIDENCE||'.local-validation/v06/snow-browser';await fs.mkdir(out,{recursive:true});
const report={kind:'ASSIGNED_PHYSICAL_CARDS_REAL_UI_AND_CONTROLLER_NOT_NATURAL_RUN',checks:[],captures:[],browsers:[],errors:[]};
for(const [name,type]of Object.entries({chromium,firefox,webkit})){
 const browser=await type.launch({headless:true});report.browsers.push({name,version:browser.version()});const context=await browser.newContext({viewport:{width:1366,height:768},recordVideo:name==='chromium'?{dir:out}:undefined});const page=await context.newPage();page.setDefaultTimeout(20000);page.on('pageerror',e=>report.errors.push(name+': '+e.message));
 const check=id=>{report.checks.push({id,browser:name,status:'PASS'});console.log('PASS',name,id);},capture=async id=>{const file=name+'-'+id+'.png';await page.screenshot({path:out+'/'+file,fullPage:true});report.captures.push(file);};
 try{
 await page.goto('http://127.0.0.1:5173/');await page.locator('#start-run').waitFor();
 await page.evaluate(async()=>{
  const [{assignedSnow,placeAssigned},{RunController},{renderCombat},{openDeck,openRecords,openSaves},{LocalStore,newProfile},{registry},{playAttack,createDOMPresentation},{renderIntro},{renderShop}]=await Promise.all([import('/tests/helpers/snow-state.js'),import('/src/game/runController.js'),import('/src/ui/combat.js'),import('/src/ui/overlays.js'),import('/src/services/localStore.js'),import('/src/data/language/index.js'),import('/src/engine/presentation.js'),import('/src/ui/progression.js'),import('/src/ui/shop.js')]);
  const store=new LocalStore({registry});await store.init();
  window.snow={root:document.querySelector('#app'),store,c:assignedSnow(4),selected:new Set(),options:{speed:2,effectsOff:false},async reset(round=4){this.c=assignedSnow(round);this.profile=this.c.getProfile();await store.saveProfile(this.profile);this.show();},show(state=this.c.getState(),locked=false){this.view?.cleanup();this.view=renderCombat(this.root,state,{selected:this.selected,locked,command:cmd=>this.command(cmd),openOverlay:kind=>{if(['draw','discard','deck'].includes(kind))openDeck(this.c.getState(),kind);else if(kind==='records')openRecords(this.c.getProfile(),this.c.getState());else if(kind==='saves')openSaves({store,profile:this.profile,state:this.c.getState(),onLoad:s=>{this.c=new RunController({initialState:s,profile:this.profile});this.show();}});}});},async command(cmd){const before=this.c.getState(),r=this.c.dispatch(cmd);if(!r.ok)throw Error(r.message);if(r.resolution){this.last=r.resolution;this.show(before,true);await playAttack(r.resolution,createDOMPresentation(this.root),this.options);this.c.dispatch({type:'FINISH_PRESENTATION',attackId:r.resolution.attackId});}this.show();return r;},place(text,polish=0){placeAssigned(this.c,text,{polish});this.show();},intro(){const s=this.c.getState();s.combat=null;s.status='STAGE_INTRO';renderIntro(this.root,s,{onStart:()=>{}});},shop(){const s=this.c.getState();s.combat=null;s.status='SHOP';s.shop.closed=false;renderShop(this.root,s,{command:()=>({ok:true})});}};
  await snow.reset();
 });
 const initial=await page.evaluate(()=>snow.c.getState());assert.equal(initial.combat.temporaryCardIds.length,8);assert.ok(await page.locator('.hand-cards .frost-card').count()>=2);assert.match(await page.locator('.frost-crystals').innerText(),/빙결핵 5 \/ 5/);await capture('boss-opening');check('P058_P066_P130_P131_P136_BOSS_OPENING');
 await page.getByRole('button',{name:'빙정과 거울뿔 사슴'}).click();assert.match(await page.locator('dialog').innerText(),/체력은 1/);await page.keyboard.press('Escape');
 const frost=initial.combat.handIds.find(id=>initial.combat.temporaryCardIds.includes(id));await page.locator(`[data-card-id="${frost}"] .card-body`).click();assert.ok((await page.evaluate(()=>snow.c.getState())).combat.sentenceSlots.some(s=>s.cardInstanceId===frost));await page.locator(`.combat-sentence [data-card-id="${frost}"] .card-body`).click();assert.ok((await page.evaluate(()=>snow.c.getState())).combat.handIds.includes(frost));
 const box=await page.locator(`.hand-cards [data-card-id="${frost}"] .card-body`).boundingBox(),target=await page.locator('.combat-sentence').boundingBox();await page.mouse.move(box.x+box.width/2,box.y+box.height/2);await page.mouse.down();await page.mouse.move(target.x+target.width/2,target.y+target.height/2,{steps:12});await page.mouse.up();assert.equal(await page.locator('.combat-sentence .frost-card').count(),1);check('P036_CLICK_RETURN_DRAG_PHYSICAL_FROST');
 await page.evaluate(()=>snow.reset());await page.locator(`.hand-cards .frost-card .card-select`).first().click();await page.locator('#discard-selected').click();assert.equal((await page.evaluate(()=>snow.c.getState())).combat.exchangesRemaining,3);check('P037_FROST_DISCARD_CHECK_EXCHANGE');
 await page.evaluate(()=>snow.place('I am as good as you.'));const before=await page.evaluate(()=>snow.c.getState());await page.locator('#attack-submit').click();await expect(page.locator('.frost-crystals')).toContainText('빙결핵 3 / 5',{timeout:30000});await expect(page.locator('.presentation-locked')).toHaveCount(0,{timeout:30000});assert.equal((await page.evaluate(()=>snow.c.getState())).combat.shatteredTemporaryIds.length,2);assert.equal((await page.evaluate(()=>snow.last)).frostCrystalResult.brokenCrystalCount,2);await capture('two-crystals-broken');check('P115_P135_P137_TWO_REAL_COPIES_SHATTER');
 await page.getByRole('button',{name:'저장',exact:true}).click();await page.getByRole('button',{name:'슬롯 1 저장',exact:true}).click();await page.locator('dialog [role=status]').filter({hasText:'저장했습니다'}).waitFor();await page.keyboard.press('Escape');const saved=await page.evaluate(()=>snow.c.getState());await page.evaluate(()=>snow.command({type:'PREPARE'}));await page.getByRole('button',{name:'저장',exact:true}).click();await page.getByRole('button',{name:'슬롯 1 불러오기',exact:true}).click();await expect(page.locator('dialog[open]')).toHaveCount(0);assert.deepEqual(await page.evaluate(()=>snow.c.getState()),saved);check('P054_P056_P127_REAL_INDEXEDDB_RESTORE_AFTER_SHATTER');
 await page.evaluate(()=>snow.place('I need more water.'));await page.locator('#attack-submit').click();await expect(page.locator('.frost-crystals')).toContainText('빙결핵 2 / 5',{timeout:30000});await expect(page.locator('.presentation-locked')).toHaveCount(0);assert.ok(!(await page.evaluate(()=>snow.last)).analysis.grammarHits.some(h=>h.tag.startsWith('COMPARISON.')));check('P116_NONCOMPARISON_MORE_WATER');
 if(name==='chromium'){
  await page.evaluate(()=>snow.reset());await page.evaluate(()=>snow.place('I had played games and she will have played music.',3));await page.locator('#attack-submit').click();await page.waitForFunction(()=>document.querySelector('[data-presentation=label]')?.textContent.includes('빙결핵이 HP 1을 보호'),null,{timeout:45000,polling:'raf'});await capture('hp-one-lock');await expect(page.locator('.presentation-locked')).toHaveCount(0);assert.equal((await page.evaluate(()=>snow.last)).overkill,0);check('P121_P123_P138_HP_ONE_LOCK_REASON');
  for(const text of ['I am as good as you.','I need more water.','I read books twice.','I am good enough.']){await page.evaluate(text=>snow.place(text),text);await page.locator('#attack-submit').click();await expect(page.locator('.presentation-locked')).toHaveCount(0,{timeout:35000});}
  assert.equal((await page.evaluate(()=>snow.c.getState())).status,'REWARD');assert.equal((await page.evaluate(()=>snow.last)).killed,true);await capture('last-crystal-kill');check('P125_LAST_CRYSTAL_SAME_ATTACK_KILL');
  await page.evaluate(()=>snow.reset(2));await page.evaluate(()=>snow.intro());assert.match(await page.locator('.intro-page').innerText(),/세 번째 상점/);await capture('snow-intro');await page.evaluate(()=>snow.shop());assert.match(await page.locator('.shop-page').innerText(),/세 번째 상점/);assert.equal(await page.locator('.shop-item').count(),5);await capture('third-shop');check('P018_P019_P021_THIRD_SHOP_UI');
  await page.evaluate(()=>snow.reset());await page.evaluate(()=>snow.place('I am bigger than you.'));await page.locator('.combat-sentence [data-lexeme-id="lex.big.adjective"] .form-button').click();assert.deepEqual(await page.locator('.form-group h3').allTextContents(),['원급','비교급','최상급']);assert.deepEqual(await page.locator('.form-choice strong').allTextContents(),['big','bigger','biggest']);await capture('comparison-forms');await page.keyboard.press('Escape');check('P080_P142_GROUPED_REVIEWED_FORMS');
  await page.evaluate(()=>snow.reset());const inspectionBefore=await page.evaluate(()=>snow.c.getState());
  await page.locator('.pile-button:not(.pile-discard)').click();assert.ok(await page.locator('dialog .frost-card').count()>0);assert.match(await page.locator('dialog').innerText(),/영구 보유 0장/);await capture('frost-pile-ownership');await page.keyboard.press('Escape');
  await page.getByRole('button',{name:'도감',exact:true}).click();const guide=await page.locator('dialog').innerText();for(const text of ['more + 원급','the most','as + 원급 + as','too / enough'])assert.ok(guide.includes(text),text);assert.doesNotMatch(guide,/VALID|INVALID_CORE|UNSUPPORTED|cap\./);await capture('comparison-codex');await page.keyboard.press('Escape');assert.deepEqual(await page.evaluate(()=>snow.c.getState()),inspectionBefore);check('P140_P141_P143_FIXED_GUIDES_AND_TEMPORARY_OWNERSHIP');
  for(const width of [1280,1366,1920])for(const hand of [10,14]){await page.setViewportSize({width,height:width===1280?800:width===1920?1080:768});await page.evaluate(hand=>{const s=snow.c.getState();s.combat.sentenceSlots=[];s.combat.handIds=[...s.combat.temporaryCardIds,...s.activeCardIds.slice(0,hand-8)];s.combat.rulesSnapshot.handLimit=hand;snow.show(s);},hand);const geometry=await page.evaluate(()=>{const action=document.querySelector('.combat-actions').getBoundingClientRect(),hand=document.querySelector('.hand-cards').getBoundingClientRect();return {overlap:action.bottom>hand.top,hidden:[...document.querySelectorAll('.hand-cards .card-select')].some(n=>{const r=n.getBoundingClientRect();return r.height<25||r.width<25;}),scroll:document.documentElement.scrollWidth>innerWidth+1};});assert.equal(geometry.overlap,false);assert.equal(geometry.hidden,false);assert.equal(geometry.scroll,false);await capture('cards-'+width+'-'+hand);check('P130_P132_LAYOUT_'+width+'_'+hand);}
 }
 assert.deepEqual(report.errors,[]);
 }catch(e){report.status='FAIL';report.failure={browser:name,error:e.stack};await capture('failure');throw e;}
 finally{await context.close();await browser.close();await fs.writeFile(out+'/report.json',JSON.stringify(report,null,2));}
}
report.status='PASS';await fs.writeFile(out+'/report.json',JSON.stringify(report,null,2));console.log('Snow browser PASS',report.checks.length,'checks',report.captures.length,'captures');
