import {useLegacyCampaign} from './helpers/legacy-browser.mjs';
/** Required real Chromium UI interactions. Synthetic capacity rendering is explicitly separated. */
import { chromium } from '@playwright/test';
import assert from 'node:assert/strict';
import {mkdir,writeFile} from 'node:fs/promises';
import {fileURLToPath} from 'node:url';
const base=process.env.SB_UI_URL||'http://127.0.0.1:5173/';
const evidence=new URL('../docs/evidence-0.1.1/',import.meta.url);await mkdir(evidence,{recursive:true});
const browser=await chromium.launch({headless:true,args:['--no-sandbox']});
const report={environment:{browser:browser.version(),kind:'HEADLESS_CHROMIUM_NOT_PHYSICAL_TABLET'},checks:[],screenshots:[],latency:[]};
const check=(id,description,extra={})=>report.checks.push({id,description,status:'PASS',...extra});
async function screenshot(page,name){const path=fileURLToPath(new URL(`${name}.png`,evidence));await page.screenshot({path,fullPage:true});report.screenshots.push(`docs/evidence-0.1.1/${name}.png`);}
async function state(page){return page.evaluate(()=>window.__SB_DEV__.getState());}
try{
 for(const [w,h] of [[1366,768],[1920,1080],[1024,768],[1180,820]]){
  const context=await browser.newContext({viewport:{width:w,height:h}});const page=await context.newPage();await useLegacyCampaign(page);const errors=[];page.on('pageerror',e=>errors.push(e.message));
  await page.goto(`${base}?debug=1#lobby`);await page.locator('#start-run').waitFor();await screenshot(page,`ui-${w}-lobby`);
  await page.getByLabel('플레이어 이름').fill(`UI ${w}`);await page.getByText('원정 시드 직접 입력').click();await page.getByLabel('선택 시드').fill('ui-layout-01');await page.locator('#start-run').click();await page.locator('#start-battle').click();await page.locator('.game-shell').waitFor();await page.getByRole('button',{name:'안내 건너뛰기',exact:true}).click();
  let s=await state(page);assert.equal(s.combat.handIds.length,6);assert.equal(s.combat.sentenceSlots.length,0);await screenshot(page,`ui-${w}-edit`);
  const geometry=await page.evaluate(()=>{const mid=document.querySelector('.combat-middle').getBoundingClientRect(),hand=document.querySelector('.hand-section').getBoundingClientRect();return {width:document.body.scrollWidth,height:document.body.scrollHeight,viewportWidth:innerWidth,viewportHeight:innerHeight,middleBottom:mid.bottom,handTop:hand.top};});assert.ok(geometry.width<=w+1,'no horizontal overflow');assert.ok(geometry.middleBottom<=geometry.handTop+1,'middle and hand do not overlap');
  check(`VIEWPORT_${w}`,`${w}×${h} lobby/edit layout readable`,geometry);
  const id=s.combat.handIds[0],body=page.locator(`[data-card-id="${id}"] .card-body`);const t=performance.now();await body.click();report.latency.push({viewport:w,action:'click_roundtrip_upper_bound',ms:performance.now()-t});
  s=await state(page);assert.equal(s.combat.sentenceSlots.length,1);assert.equal(await page.locator('[data-presentation=score]').isVisible(),false);assert.equal(await page.locator('.presentation-role').count(),0);check(`U01_${w}`,'editing reveals no grammar role, correctness, score, or combo');
  await page.locator(`[data-card-id="${id}"] .form-button`).click();await page.locator('dialog').waitFor();await screenshot(page,`ui-${w}-form`);assert.equal((await state(page)).combat.sentenceSlots.length,1);check(`U02_${w}`,'form button opens menu without returning card');await page.keyboard.press('Escape');await page.locator('dialog').waitFor({state:'hidden'});assert.equal(await page.locator('dialog[open]').count(),0);
  const handId=(await state(page)).combat.handIds[0];await page.locator(`[data-card-id="${handId}"] .card-select`).click();await screenshot(page,`ui-${w}-exchange`);s=await state(page);assert.equal(s.combat.sentenceSlots.length,1);assert.equal(s.combat.handIds.length,5);assert.equal(await page.locator('.word-card.selected').count(),1);check(`U03_${w}`,'exchange selection does not add to sentence');await page.locator('#clear-card-selection').click();
  await page.getByRole('button',{name:'내 덱',exact:true}).click();await page.locator('dialog').waitFor();assert.equal(await page.locator('dialog .card-body[tabindex="0"]').count(),0);await page.keyboard.press('Escape');await page.locator('dialog').waitFor({state:'hidden'});await page.getByRole('button',{name:/DRAW/}).click();assert.ok((await page.locator('dialog').innerText()).includes('순서는 공개하지 않음'));await page.keyboard.press('Escape');await page.locator('dialog').waitFor({state:'hidden'});check(`U10_${w}`,'piles are read only, draw order hidden');
  if(w===1366){
    await page.evaluate(()=>{window.__uiFeedback=[];document.addEventListener('click',event=>{const card=event.target.closest('.card-body')?.closest('.word-card');if(!card)return;const started=performance.now(),id=card.dataset.cardId,zone=card.dataset.zone;requestAnimationFrame(()=>{const current=[...document.querySelectorAll('.word-card')].find(n=>n.dataset.cardId===id);if(current&&current.dataset.zone!==zone)window.__uiFeedback.push(performance.now()-started);});},true);});
    const measuredId=(await state(page)).combat.handIds[0];for(let n=0;n<30;n++)await page.locator(`[data-card-id="${measuredId}"] .card-body`).click();
    const samples=await page.evaluate(()=>window.__uiFeedback);const sorted=[...samples].sort((a,b)=>a-b);report.feedbackTiming={measurement:'Card click capture to next requestAnimationFrame with DOM zone changed; desktop headless, not hardware end-to-end latency',samples:samples.length,p50Ms:sorted[Math.ceil(sorted.length*.5)-1],p95Ms:sorted[Math.ceil(sorted.length*.95)-1],maxMs:sorted.at(-1)};assert.ok(samples.length>=28);check('UI_FEEDBACK_TIMING','30 real card clicks measured to next frame',report.feedbackTiming);
    s=await state(page);const dragId=s.combat.handIds[0];const source=await page.locator(`[data-card-id="${dragId}"] .card-body`).boundingBox();const target=await page.locator('[data-card-zone=sentence]').boundingBox();
    await page.mouse.move(source.x+source.width/2,source.y+40);await page.mouse.down();await page.mouse.move(target.x+target.width-25,target.y+target.height/2,{steps:8});await page.mouse.up();
    s=await state(page);assert.equal(s.combat.sentenceSlots.filter(x=>x.cardInstanceId===dragId).length,1);assert.ok(!s.combat.handIds.includes(dragId));check('U04','mouse drag and subsequent click move exactly once');
    const gapId=s.combat.handIds[0],ga=await page.locator(`[data-card-id="${gapId}"] .card-body`).boundingBox(),left=await page.locator('[data-card-zone=sentence] .word-card').nth(0).boundingBox(),right=await page.locator('[data-card-zone=sentence] .word-card').nth(1).boundingBox();await page.mouse.move(ga.x+ga.width/2,ga.y+35);await page.mouse.down();await page.mouse.move((left.x+left.width+right.x)/2,left.y+35,{steps:8});await page.mouse.up();s=await state(page);assert.equal(s.combat.sentenceSlots[1].cardInstanceId,gapId);check('U04_GAP','drop in actual whitespace between cards inserts at that position');
    const cancelId=s.combat.handIds[0],before=JSON.stringify(s.combat);const cancelSource=await page.locator(`[data-card-id="${cancelId}"] .card-body`).boundingBox();await page.mouse.move(cancelSource.x+30,cancelSource.y+35);await page.mouse.down();await page.mouse.move(cancelSource.x+60,cancelSource.y-30,{steps:5});await page.locator(`[data-card-id="${cancelId}"] .card-body`).dispatchEvent('pointercancel',{pointerId:1,bubbles:true});await page.mouse.up();assert.equal(JSON.stringify((await state(page)).combat),before);check('D17','pointercancel leaves every card in original pile once');
    const keyId=(await state(page)).combat.handIds[0];await page.locator(`[data-card-id="${keyId}"] .card-body`).focus();await page.keyboard.press('Enter');assert.ok((await state(page)).combat.sentenceSlots.some(x=>x.cardInstanceId===keyId));check('U06_KEYBOARD','focused card + Enter moves; Escape closes form menu');
    const beforeResize=JSON.stringify((await state(page)).combat);await page.setViewportSize({width:1024,height:768});assert.equal(JSON.stringify((await state(page)).combat),beforeResize);check('U05','resize preserves card identities, order, and game state');await page.setViewportSize({width:w,height:h});
    // A separate readonly/captured-command renderer fixture checks maxima; never touches the live controller.
    await page.evaluate(async()=>{const {renderCombat}=await import('/src/ui/combat.js');const actual=window.__SB_DEV__.getState(),ids=actual.activeCardIds;const fixture=structuredClone(actual);fixture.combat.handIds=ids.slice(16,26);fixture.combat.sentenceSlots=ids.slice(0,16).map(cardInstanceId=>({cardInstanceId,selection:null}));fixture.combat.drawIds=ids.slice(26);fixture.combat.discardIds=[];fixture.combat.phase='EDIT';fixture.tutorial.visible=false;fixture.runes={slotLimit:3,orderedInstanceIds:['r0','r1','r2'],instances:{r0:{instanceId:'r0',runeId:'rune.svc',level:3},r1:{instanceId:'r1',runeId:'rune.polished',level:3},r2:{instanceId:'r2',runeId:'rune.adverbs',level:3}}};window.__fixtureState=fixture;window.__fixtureCommands=[];const holder=document.createElement('div');document.querySelector('#app').replaceChildren(holder);renderCombat(holder,fixture,{command:c=>window.__fixtureCommands.push(c),openOverlay:()=>{},selected:new Set()});const badge=document.createElement('aside');badge.textContent='UI 합성 fixture · 실제 원정/기록 아님';badge.style='position:fixed;top:0;left:0;background:#e6ce85;color:#173421;padding:3px;font-size:11px;z-index:10';document.body.append(badge);});
    for(const [cw,ch] of [[1366,768],[1920,1080],[1024,768],[1180,820]]){await page.setViewportSize({width:cw,height:ch});await screenshot(page,`ui-capacity-${cw}-synthetic`);const capacityGeometry=await page.evaluate(()=>({actionBottom:document.querySelector('.combat-actions').getBoundingClientRect().bottom,handTop:document.querySelector('.hand-section').getBoundingClientRect().top,width:document.body.scrollWidth,height:document.body.scrollHeight}));assert.ok(capacityGeometry.actionBottom<=capacityGeometry.handTop+1,`${cw} capacity actions must not overlap hand`);assert.ok(capacityGeometry.width<=cw+1);check(`CAPACITY_${cw}`,'16 sentence + 10 hand synthetic layout has separate controls/hand',capacityGeometry);}await page.setViewportSize({width:1024,height:768});
    for(const [cw,ch]of [[1920,1080],[1366,768],[1180,820],[1024,768]]){
      await page.evaluate(async()=>{const {renderCombat}=await import('/src/ui/combat.js');const s=structuredClone(window.__fixtureState);for(let i=0;i<4;i++){const id=`capacity.extra.${i}`;s.cardInstances[id]={...s.cardInstances[s.activeCardIds[i]],instanceId:id};s.activeCardIds.push(id);s.combat.handIds.push(id);}s.combat.rulesSnapshot.handLimit=14;renderCombat(document.querySelector('#app'),s,{command:c=>window.__fixtureCommands.push(c),openOverlay:()=>{}});});
      await page.setViewportSize({width:cw,height:ch});assert.equal(await page.locator('.hand-cards .word-card').count(),14);await screenshot(page,`capacity-14-${cw}`);
      const g=await page.evaluate(()=>({bottom:document.querySelector('.combat-actions').getBoundingClientRect().bottom,hand:document.querySelector('.hand-section').getBoundingClientRect().top,width:document.body.scrollWidth,font:getComputedStyle(document.querySelector('.status-nav button')).fontSize,rune:getComputedStyle(document.querySelector('.rune-effect')).fontSize}));assert.ok(g.bottom<=g.hand+1,JSON.stringify(g));assert.ok(g.width<=cw+1);assert.equal(g.font,'14px');assert.ok(parseFloat(g.rune)>=12);check(`P45_14_${cw}`,'14 hand + 16 sentence + three runes, larger side fonts',g);
    }
    await page.evaluate(async()=>{const {renderCombat}=await import('/src/ui/combat.js');renderCombat(document.querySelector('#app'),window.__fixtureState,{command:c=>window.__fixtureCommands.push(c),openOverlay:()=>{}});});
    assert.equal(await page.locator('[data-card-zone=sentence] .word-card').count(),16);assert.equal(await page.locator('[data-card-zone=hand] .word-card').count(),10);
    const sourceCard=page.locator('[data-card-zone=hand] .word-card').first(),targetCard=page.locator('[data-card-zone=sentence] .word-card').first();const sr=await sourceCard.locator('.card-body').boundingBox(),tr=await targetCard.locator('.card-body').boundingBox();await page.mouse.move(sr.x+sr.width/2,sr.y+sr.height/2);await page.mouse.down();await page.mouse.move(tr.x+tr.width/2,tr.y+tr.height/2,{steps:8});await page.mouse.up();assert.equal(await page.evaluate(()=>window.__fixtureCommands.at(-1)?.type),'SWAP_CARDS');check('D14_UI','10 hand + 16 sentence synthetic renderer exposes direct body-drop swap');
  }
  assert.deepEqual(errors,[]);check(`BROWSER_ERRORS_${w}`,'no browser uncaught errors');await context.close();
 }
 // Genuine CDP touch stream, with mouse emulation disabled for the interaction.
 const touch=await browser.newContext({viewport:{width:1024,height:768},hasTouch:true,isMobile:false});const page=await touch.newPage();await useLegacyCampaign(page);await page.goto(`${base}?debug=1#lobby`);await page.locator('#start-run').waitFor();await page.getByLabel('플레이어 이름').fill('터치 검사');await page.locator('#start-run').tap();await page.locator('#start-battle').tap();await page.getByRole('button',{name:'안내 건너뛰기',exact:true}).tap();let s=await state(page);const id=s.combat.handIds[0];await page.locator(`[data-card-id="${id}"] .card-body`).tap();assert.equal((await state(page)).combat.sentenceSlots.length,1);const dragId=(await state(page)).combat.handIds[0];const a=await page.locator(`[data-card-id="${dragId}"] .card-body`).boundingBox(),z=await page.locator('[data-card-zone=sentence]').boundingBox();const cdp=await touch.newCDPSession(page);await cdp.send('Input.dispatchTouchEvent',{type:'touchStart',touchPoints:[{x:a.x+a.width/2,y:a.y+35,id:1}]});for(let i=1;i<=8;i++)await cdp.send('Input.dispatchTouchEvent',{type:'touchMove',touchPoints:[{x:a.x+a.width/2+(z.x+z.width-20-a.x-a.width/2)*i/8,y:a.y+35+(z.y+z.height/2-a.y-35)*i/8,id:1}]});await cdp.send('Input.dispatchTouchEvent',{type:'touchEnd',touchPoints:[]});s=await state(page);assert.equal(s.combat.sentenceSlots.filter(x=>x.cardInstanceId===dragId).length,1);const touchBefore=JSON.stringify(s.combat),cancelId=s.combat.handIds[0],box=await page.locator(`[data-card-id="${cancelId}"] .card-body`).boundingBox();await cdp.send('Input.dispatchTouchEvent',{type:'touchStart',touchPoints:[{x:box.x+20,y:box.y+25,id:2}]});await cdp.send('Input.dispatchTouchEvent',{type:'touchMove',touchPoints:[{x:box.x+50,y:box.y-35,id:2}]});await cdp.send('Input.dispatchTouchEvent',{type:'touchCancel',touchPoints:[]});assert.equal(await page.locator('.drag-ghost').count(),0);assert.equal(JSON.stringify((await state(page)).combat),touchBefore);await page.setViewportSize({width:1180,height:820});assert.equal(await page.locator('.drag-ghost').count(),0);await page.setViewportSize({width:1024,height:768});check('P10_TOUCH_CANCEL','CDP touchCancel and resize clear drag nodes without state mutation');check('U06_TOUCH','Chromium touch emulation tap and pointer drag work (not a physical iPad test)');await screenshot(page,'ui-touch-1024');await touch.close();
 report.status='PASS';
}catch(error){report.status='FAIL';report.error=error.stack;throw error;}
finally{await writeFile(new URL('ui-browser.json',evidence),JSON.stringify(report,null,2));await browser.close();console.log(JSON.stringify({status:report.status,checks:report.checks.length,screenshots:report.screenshots.length}));}
