import test from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs';
import {RunController} from '../src/game/runController.js';
import {applyTurnHandSeal,isTurnSealed,validateTurnHandSeal} from '../src/game/turnHandSeal.js';
import {assertRunInvariants} from '../src/game/invariants.js';
import {createRng,nextFloat} from '../src/game/rng.js';
import {registryForVersion} from '../src/data/language/index.js';
import {validateRunState,canSaveRun} from '../src/services/localStore.js';
import {assignedSphinx,assignedAttack,act} from './helpers/desert-state.js';
const fixtures=JSON.parse(fs.readFileSync(new URL('./fixtures/v05-seal-expectations.json',import.meta.url),'utf8')).items;
const fixture=id=>fixtures.find(row=>row.id===id);
const check=(id,fn)=>test(`0.5 seal ${id}: ${fixture(id).title}`,fn);
const language=registryForVersion('0.5.0');
let base;
function controller(){base??=assignedSphinx().getState();return new RunController({initialState:structuredClone(base)});}
const seal=c=>c.getState().combat.enemyState.bossMechanic;
const freeWord=c=>c.getState().combat.handIds.find(id=>id!==seal(c).sealedCardId&&!c.getState().cardInstances[id].cardDefId.startsWith('card.operation.'));
function operation(c,kind='supply'){
 const s=c.getState(),id=`assigned.operation.${kind}`;s.cardInstances[id]={instanceId:id,cardDefId:`card.operation.${kind}`,polishLevel:0,specialEffectId:null};s.activeCardIds.push(id);s.combat.handIds.push(id);c._state=s;return id;
}
function use(c,id,targetCardId){const s=c.getState();const r=act(c,{type:'USE_OPERATION',sourceCardId:id,targetCardId,expectedRevision:s.revision,battleId:s.combat.enemyState.id});act(c,{type:'FINISH_OPERATION',effectId:r.operationEffect.effectId});return r;}
function moveSeal(c,pile){const s=c.getState(),id=seal(c).sealedCardId;for(const k of ['handIds','drawIds','discardIds'])s.combat[k]=s.combat[k].filter(x=>x!==id);s.combat[pile].push(id);c._state=s;return id;}
function model(row){
 const initial=row.initial,all=[...new Set([...(initial.hand??[]),...(initial.board??[]),...(initial.previous?[initial.previous]:[])])];
 let rng;for(let i=0;i<100;i++){rng=createRng('seal.contract.'+i);const value=nextFloat(structuredClone(rng.encounter));const length=row.expected.eligible.length;if(!length||Math.floor(value*length)===Math.floor((initial.draw??0)*length))break;}
 const run={version:'0.5.0',status:'BATTLE',progress:{stageId:'stage.05',battleNumber:22},activeCardIds:all,cardInstances:Object.fromEntries(all.map(id=>[id,{instanceId:id,cardDefId:initial.kinds?.[id]==='OPERATION'?'card.operation.supply':'card.book',polishLevel:0,specialEffectId:null}])),rng,combat:{handIds:initial.hand??[],sentenceSlots:(initial.board??[]).map(cardInstanceId=>({cardInstanceId})),turnIndex:1,turnsRemaining:6,rulesSnapshot:{turnLimit:6},enemyState:{id:'battle.05.05',hp:840,bossMechanic:{id:'TURN_HAND_SEAL',sealedCardId:initial.previous??null}}}};
 return run;
}
for(const id of ['B001','B002','B003','B004','B014'])check(id,()=>{const row=fixture(id),run=model(row),before=structuredClone(run.rng),board=structuredClone(run.combat.sentenceSlots);const m=applyTurnHandSeal(run);assert.deepEqual(m.history[0].candidateIds,row.expected.eligible);assert.equal(m.sealedCardId,row.expected.selected);assert.equal(run.rng.encounter.cursor-before.encounter.cursor,row.expected.encounterDraws);for(const key of ['deck','reward','shop'])assert.deepEqual(run.rng[key],before[key]);assert.deepEqual(run.combat.sentenceSlots,board);});
check('B005',()=>{const c=controller(),id=operation(c),before=seal(c),rng=c.getState().rng.encounter;use(c,id);assert.deepEqual(seal(c),before);assert.deepEqual(c.getState().rng.encounter,rng);assert.equal(validateRunState(c.getState(),language),true);});
check('B006',()=>{const c=controller(),id=seal(c).sealedCardId,before=c.getState();act(c,{type:'EXCHANGE',cardIds:[id]});const s=c.getState();assert.deepEqual(seal(c),before.combat.enemyState.bossMechanic);assert.equal(s.combat.exchangesRemaining,before.combat.exchangesRemaining-1);assert.equal(s.combat.turnsRemaining,before.combat.turnsRemaining);assert.ok(s.combat.discardIds.includes(id));assert.deepEqual(s.rng.encounter,before.rng.encounter);});
check('B007',()=>{const c=controller(),id=seal(c).sealedCardId,op=operation(c);act(c,{type:'EXCHANGE',cardIds:[id]});const s=c.getState();s.combat.discardIds=s.combat.discardIds.filter(x=>x!==id);s.combat.drawIds=[id,...s.combat.drawIds.filter(x=>x!==id)];c._state=s;use(c,op);const before=c.getState();assert.ok(before.combat.handIds.includes(id));assert.equal(c.dispatch({type:'ADD_CARD',cardId:id}).ok,false);assert.deepEqual(c.getState(),before);});
check('B008',()=>{const c=controller(),op=operation(c,'search'),id=moveSeal(c,'drawIds'),before=seal(c);use(c,op,id);assert.deepEqual(seal(c),before);assert.ok(c.getState().combat.handIds.includes(id));assert.equal(c.dispatch({type:'ADD_CARD',cardId:id}).ok,false);});
check('B009',()=>{const c=controller(),old=seal(c),before=c.getState();act(c,{type:'PREPARE'});const s=c.getState(),m=seal(c);assert.equal(s.combat.turnIndex,2);assert.equal(m.previousSealedCardId,old.sealedCardId);assert.ok(!m.history.at(-1).candidateIds.includes(old.sealedCardId));assert.ok(m.history.at(-1).candidateIds.every(id=>s.combat.handIds.includes(id)));assert.equal(m.sealSequence,2);assert.equal(s.rng.encounter.cursor,before.rng.encounter.cursor+1);});
check('B010',()=>{const c=controller(),op=operation(c),s=c.getState();s.combat.drawIds.push(...s.combat.handIds.filter(id=>id!==op));s.combat.handIds=[op];s.combat.enemyState.bossMechanic={id:'TURN_HAND_SEAL'};s.rng.encounter=createRng(s.config.seed).encounter;applyTurnHandSeal(s);c._state=s;assert.equal(seal(c).sealedCardId,null);assert.equal(s.rng.encounter.cursor,0);const before=seal(c);use(c,op);assert.deepEqual(seal(c),before);assert.equal(c.getState().rng.encounter.cursor,0);});
check('B011',()=>{const c=controller(),id=seal(c).sealedCardId,other=freeWord(c),s=c.getState();s.cardInstances[other].cardDefId=s.cardInstances[id].cardDefId;c._state=s;act(c,{type:'ADD_CARD',cardId:other});assert.ok(isTurnSealed(c.getState(),id));assert.equal(c.getState().combat.sentenceSlots[0].cardInstanceId,other);});
check('B012',()=>{const c=controller(),before=c.getState(),undo=structuredClone(c.undo);const r=c.dispatch({type:'ADD_CARD',cardId:seal(c).sealedCardId});assert.equal(r.ok,false);assert.match(r.message,/교환/);assert.deepEqual(c.getState(),before);assert.deepEqual(c.undo,undo);});
check('B013',()=>{const c=controller(),other=freeWord(c);act(c,{type:'ADD_CARD',cardId:other});const before=c.getState(),undo=structuredClone(c.undo);assert.equal(c.dispatch({type:'SWAP_CARDS',handCardId:seal(c).sealedCardId,sentenceCardId:other}).ok,false);assert.deepEqual(c.getState(),before);assert.deepEqual(c.undo,undo);});
check('B015',()=>{const c=controller();act(c,{type:'PREPARE'});act(c,{type:'PREPARE'});act(c,{type:'EXCHANGE',cardIds:[freeWord(c)]});const before=c.getState();assert.equal(before.combat.turnsRemaining,4);assert.equal(before.combat.exchangesRemaining,3);assert.equal(c.dispatch({type:'ADD_CARD',cardId:seal(c).sealedCardId}).ok,false);assert.deepEqual(c.getState(),before);});
check('B016',()=>{const c=controller(),id=freeWord(c),s=c.getState();s.cardInstances[id].cardDefId='card.book';c._state=s;act(c,{type:'ADD_CARD',cardId:id});const before=c.getState(),r=act(c,{type:'SUBMIT'}).resolution;assert.equal(r.actualHpLoss,0);assert.equal(r.analysis.status,'INVALID_CORE');assert.equal(c.getState().combat.turnsRemaining,before.combat.turnsRemaining-1);assert.ok(c.getState().combat.discardIds.includes(id));assert.equal(seal(c).sealSequence,1);act(c,{type:'FINISH_PRESENTATION',attackId:r.attackId});assert.equal(seal(c).sealSequence,2);assert.equal(c.getState().rng.encounter.cursor,before.rng.encounter.cursor+1);});
check('B017',()=>{const c=controller();while(c.getState().combat.turnsRemaining>1)act(c,{type:'PREPARE'});const rng=c.getState().rng.encounter;const r=assignedAttack(c,'I had played games and she will have played music');assert.equal(r.killed,true);assert.equal(c.getState().status,'REWARD');assert.equal(c.getState().combat.turnsRemaining,0);assert.deepEqual(c.getState().rng.encounter,rng);assert.equal(isTurnSealed(c.getState(),seal(c).sealedCardId),false);});
check('B018',()=>{const c=controller();while(c.getState().combat.turnsRemaining>1)act(c,{type:'PREPARE'});const before=c.getState();assert.equal(c.dispatch({type:'PREPARE'}).needsConfirmation,true);assert.deepEqual(c.getState(),before);act(c,{type:'PREPARE',confirmed:true});assert.equal(c.getState().status,'DEFEAT');assert.deepEqual(c.getState().rng,before.rng);assert.equal(seal(c).sealSequence,6);});
check('B019',()=>{const c=controller(),s=c.getState(),before=structuredClone(s);applyTurnHandSeal(s);applyTurnHandSeal(s);assert.deepEqual(s,before);});
check('B020',()=>{const c=controller(),s=c.getState();assert.equal(canSaveRun(s),true);const loaded=new RunController({initialState:JSON.parse(JSON.stringify(s))});assert.deepEqual(loaded.getState(),s);assert.ok(loaded.restoreRun(s).ok);assert.deepEqual(loaded.getState(),s);});
check('B021',()=>{for(const pile of ['discardIds','drawIds']){const c=controller();moveSeal(c,pile);const s=c.getState();assert.equal(validateRunState(s,language),true);assert.equal(validateTurnHandSeal(s),true);assert.deepEqual(new RunController({initialState:JSON.parse(JSON.stringify(s))}).getState(),s);}});
check('B022',()=>{const c=controller(),id=operation(c),s=c.getState();s.combat.enemyState.bossMechanic.sealedCardId=id;assert.throws(()=>validateRunState(s,language));for(const mutate of [s=>s.combat.enemyState.bossMechanic.sealedCardId='unknown',s=>s.combat.enemyState.bossMechanic.sealedForTurnIndex=2,s=>s.combat.enemyState.bossMechanic.history.push(s.combat.enemyState.bossMechanic.history[0]),s=>s.combat.enemyState.bossMechanic.lastAppliedTurnKey='battle.05.05:2',s=>s.combat.enemyState.bossMechanic.history[0].candidateIds=['unknown']]){const bad=c.getState();mutate(bad);assert.throws(()=>validateRunState(bad,language));}});
check('B023',()=>{const c=controller(),id=seal(c).sealedCardId,s=c.getState();s.combat.handIds=s.combat.handIds.filter(x=>x!==id);s.combat.sentenceSlots=[{cardInstanceId:id,selection:null}];assert.throws(()=>assertRunInvariants(s,language));assert.throws(()=>validateRunState(s,language));});
check('B024',()=>{const c=controller();act(c,{type:'PREPARE'});act(c,{type:'ADD_CARD',cardId:freeWord(c)});const before=c.getState(),undo=structuredClone(c.undo),commit=c._commit;let proposal;c._commit=next=>{proposal=structuredClone(next);throw Error('assigned invariant failure after draw/seal');};const r=c.dispatch({type:'PREPARE'});c._commit=commit;assert.equal(r.ok,false);assert.equal(r.analysis.status,'ENGINE_ERROR');assert.equal(proposal.combat.turnIndex,before.combat.turnIndex+1);assert.equal(proposal.rng.encounter.cursor,before.rng.encounter.cursor+1);assert.deepEqual(c.getState(),before);assert.deepEqual(c.undo,undo);});
check('B025',()=>{const c=controller();assignedAttack(c,'I had played games and she will have played music');assert.equal(isTurnSealed(c.getState(),seal(c).sealedCardId),false);act(c,{type:'NEW_RUN',config:{seed:'fresh-after-seal'}});assert.equal(c.getState().combat,null);assert.equal(isTurnSealed(c.getState(),'anything'),false);act(c,{type:'START_BATTLE'});assert.equal(c.getState().combat.enemyState.bossMechanic,undefined);assert.equal(c.getState().rng.encounter.cursor,0);});
check('B026',()=>{const c=controller(),op=operation(c,'search');act(c,{type:'ADD_CARD',cardId:freeWord(c)});const before=c.getState(),undo=structuredClone(c.undo);act(c,{type:'OPEN_OPERATION',sourceCardId:op});act(c,{type:'CANCEL_OPERATION'});assert.deepEqual(c.getState(),before);assert.deepEqual(c.undo,undo);});
test('0.5 seal editing/forms/runes/undo and stale callbacks never reroll; kept board is excluded on prepare',()=>{
 const c=controller(),id=freeWord(c),before=seal(c);act(c,{type:'ADD_CARD',cardId:id});const s=c.getState(),form=language.lexemeById[language.cardById[s.cardInstances[id].cardDefId].lexemeId].formIds[0];act(c,{type:'SET_FORM',cardId:id,formId:form});act(c,{type:'UNDO'});act(c,{type:'REORDER_RUNES',instanceIds:[]});assert.deepEqual(seal(c),before);const state=c.getState();for(const command of [{type:'PREPARE',expectedRevision:0},{type:'PREPARE',battleId:'battle.01.01'},{type:'FINISH_PRESENTATION',attackId:'old'},{type:'FINISH_OPERATION',effectId:'old'}]){assert.equal(c.dispatch(command).ok,false);assert.deepEqual(c.getState(),state);}act(c,{type:'PREPARE'});assert.ok(!seal(c).history.at(-1).candidateIds.includes(id));assert.ok(c.getState().combat.sentenceSlots.some(slot=>slot.cardInstanceId===id));
});
test('0.5 seal identical seeds/actions choose owned indices and identical RNG independent of random run IDs',()=>{const a=assignedSphinx('same.seal.seed'),b=assignedSphinx('same.seal.seed');for(let i=0;i<4;i++){const sa=a.getState(),sb=b.getState();assert.equal(sa.activeCardIds.indexOf(seal(a).sealedCardId),sb.activeCardIds.indexOf(seal(b).sealedCardId));assert.deepEqual(sa.rng,sb.rng);act(a,{type:'PREPARE'});act(b,{type:'PREPARE'});}});
