import test from 'node:test';import assert from 'node:assert/strict';
import {act,assignedSnow,placeAssigned,newSnow,snowLanguage} from './helpers/snow-state.js';
import {RunController} from '../src/game/runController.js';
import {validateRunState,canSaveRun,applyProfileEvent,newProfile} from '../src/services/localStore.js';
import {FROST_SUPPLIES,SNOW_PACKS} from '../src/game/mirrorSnowfield.js';
import {assertRunInvariants} from '../src/game/invariants.js';
import {searchCandidates} from '../src/game/operations.js';
import {drawCards} from '../src/game/deck.js';
import {comboEligibility} from '../src/engine/comboEligibility.js';
let initial;
function fixture(round=4){initial??=assignedSnow().getState();const c=new RunController({initialState:initial});if(round!==0){const s=c.getState();for(const id of s.combat.temporaryCardIds)delete s.cardInstances[id];s.progress.roundIndex=round;s.progress.battleNumber=23+round;s.combat=null;c._beginBattle(s);c._state=s;}return c;}
function validate(c){assert.equal(validateRunState(c.getState(),snowLanguage),true);assertRunInvariants(c.getState(),snowLanguage);}
for(let round=0;round<5;round++)test('0.6 F00'+(round+1)+' battle-scoped supply and visibility',()=>{const c=fixture(round),s=c.getState(),b=s.combat;assert.deepEqual(b.temporaryCardIds.map(id=>s.cardInstances[id].cardDefId),FROST_SUPPLIES[round].map(w=>'card.'+w));assert.ok(b.handIds.filter(id=>b.temporaryCardMeta[id]?.crystalBearing).length>=(round===4?2:1));assert.ok(!s.activeCardIds.some(id=>b.temporaryCardIds.includes(id)));if(round===4)for(let i=0;i<3;i++)assert.ok(b.drawIds.slice(i*b.rulesSnapshot.turnDraw,(i+1)*b.rulesSnapshot.turnDraw).some(id=>b.temporaryCardMeta[id]?.crystalBearing));validate(c);});
test('0.6 F006 F007 F008 F009 F016 move, return, exchange, reshuffle, prepare preserve frost',()=>{const c=fixture(),s=c.getState(),id=s.combat.handIds.find(id=>s.combat.temporaryCardIds.includes(id));act(c,{type:'ADD_CARD',cardId:id});assert.ok(c.getState().combat.sentenceSlots.some(x=>x.cardInstanceId===id));act(c,{type:'RETURN_CARD',cardId:id});assert.ok(c.getState().combat.handIds.includes(id));act(c,{type:'EXCHANGE',cardIds:[id]});assert.ok(c.getState().combat.discardIds.includes(id));const p=c.getState();p.combat.discardIds=[...p.combat.discardIds,...p.combat.drawIds];p.combat.drawIds=[];p.combat.handIds=[];p.combat.discardIds.push(...c.getState().combat.handIds);drawCards(p.combat,100,100,p.rng.deck);assert.ok(p.combat.handIds.includes(id));act(c,{type:'PREPARE'});assert.equal(c.getState().combat.shatteredTemporaryIds.length,0);validate(c);});
for(const type of ['SEARCH','SUPPLY'])test('0.6 '+(type==='SEARCH'?'F010':'F011')+' operation draws frost without turns/exchanges',()=>{const c=fixture(),s=c.getState(),b=s.combat,id=b.drawIds.find(id=>b.temporaryCardMeta[id]?.crystalBearing),source=b.handIds.find(id=>s.activeCardIds.includes(id));s.cardInstances[source].cardDefId=type==='SEARCH'?'operation.search':'operation.supply';s.cardInstances[source].polishLevel=0;const def=s.cardInstances[source].cardDefId;s.cardInstances[source].cardDefId=def.replace('operation.','card.operation.');
 // IDs follow the registered operation definitions, not new game content.
 s.cardInstances[source].cardDefId=type==='SEARCH'?'card.operation.search':'card.operation.supply';
 if(type==='SUPPLY')b.drawIds=[id,...b.drawIds.filter(x=>x!==id)];assert.ok(searchCandidates(s).some(x=>x.cardInstanceId===id));c._state=s;
 const r=act(c,{type:'USE_OPERATION',sourceCardId:source,targetCardId:id,expectedRevision:s.revision,battleId:b.enemyState.id});assert.ok(r.operationEffect.drawnCardIds.includes(id));act(c,{type:'FINISH_OPERATION',effectId:r.operationEffect.effectId});assert.equal(c.getState().combat.turnsRemaining,b.turnsRemaining);assert.equal(c.getState().combat.exchangesRemaining,b.exchangesRemaining);validate(c);});
for(const [id,text,expected,status]of [['F012','I need more water.',1,'VALID'],['F013','She need more water.',1,'VALID_WITH_ISSUES'],['F014','I am more bigger than you.',0,'VALID_WITH_ISSUES'],['F015','More.',0,'INVALID_CORE']])test('0.6 '+id+' actual submitted physical frost '+status,()=>{const c=fixture();placeAssigned(c,text);const before=c.getState(),r=act(c,{type:'SUBMIT'}).resolution;assert.equal(r.status,status);assert.equal(r.frostCrystalResult?.brokenCrystalCount??0,expected);const broken=c.getState().combat.shatteredTemporaryIds;assert.deepEqual(new Set(broken),new Set(r.consumedTemporaryCardIds));assert.ok(broken.length>0);assert.ok(!c.getState().combat.discardIds.some(id=>broken.includes(id)));act(c,{type:'FINISH_PRESENTATION',attackId:r.attackId});assert.equal(c.getState().combat.turnsRemaining,before.combat.turnsRemaining-1);validate(c);});
test('0.6 F017 F018 save/load before and after shatter preserves IDs, RNG and receipts',()=>{const c=fixture();for(let i=0;i<2;i++){validate(c);const saved=c.getState();assert.equal(canSaveRun(saved),true);assert.deepEqual(new RunController({initialState:JSON.parse(JSON.stringify(saved))}).getState(),saved);if(i===0){placeAssigned(c,'I read books twice.');const r=act(c,{type:'SUBMIT'}).resolution;act(c,{type:'FINISH_PRESENTATION',attackId:r.attackId});assert.equal(c.getState().combat.shatteredTemporaryIds.length,1);}}});
test('0.6 F019 F020 victory cleanup, fresh next battle IDs; no permanent growth',()=>{const c=fixture(0),before=c.getState();placeAssigned(c,'I had played games and she will have played music',{polish:3});const r=act(c,{type:'SUBMIT'}).resolution;act(c,{type:'FINISH_PRESENTATION',attackId:r.attackId});assert.equal(c.getState().status,'REWARD');assert.ok(before.combat.temporaryCardIds.every(id=>!c.getState().cardInstances[id]));assert.deepEqual(c.getState().activeCardIds,before.activeCardIds);validate(c);act(c,{type:'SKIP_REWARD',offerId:c.getState().reward.offerId});act(c,{type:'NEXT_BATTLE'});assert.ok(c.getState().combat.temporaryCardIds.every(id=>!before.combat.temporaryCardIds.includes(id)));validate(c);});
test('0.6 boss HP1 noncomparison crystals and same last attack kills, exact completion boundary',()=>{const c=fixture();placeAssigned(c,'I had played games and she will have played music',{polish:3,useFrost:false});let r=act(c,{type:'SUBMIT'}).resolution;assert.equal(r.enemyHpAfter,1);assert.ok(r.preventedDamage>0);assert.equal(r.overkill,0);act(c,{type:'FINISH_PRESENTATION',attackId:r.attackId});for(const text of ['I am as good as you.','I need more water.','I read books twice.','I am good enough.']){placeAssigned(c,text);r=act(c,{type:'SUBMIT'}).resolution;act(c,{type:'FINISH_PRESENTATION',attackId:r.attackId});}assert.equal(r.bossStateAfter.crystalsRemaining,0);assert.equal(r.killed,true);assert.equal(c.getState().status,'REWARD');validate(c);act(c,{type:'SKIP_REWARD',offerId:c.getState().reward.offerId});assert.equal(c.getState().progress.contentBoundary,'STAGE6_END');assert.equal(c.getState().status,'CONTENT_COMPLETE');validate(c);assert.equal(c.getProfile().stage6CompletedRunIds.length,1);});
test('0.6 defeat removes temporary objects, locked baseline cannot unlock combo',()=>{const c=fixture(),s=c.getState();s.combat.turnsRemaining=1;c._state=s;act(c,{type:'PREPARE',confirmed:true});assert.equal(c.getState().status,'DEFEAT');assert.equal(Object.values(c.getState().cardInstances).filter(x=>x.temporary).length,0);validate(c);const p=applyProfileEvent(newProfile('snow'),{type:'STAGE6_CLEAR',version:'0.6.0',runId:'once'}),n=newSnow('inherited',{profile:p});assert.ok(n.getState().eligibility.runStartUnlockBaseline.includes('pack.snowWords.reward'));assert.ok(SNOW_PACKS.every(id=>!comboEligibility(n.getState()).unlocks.includes(id)));});
test('0.6 corrupt partitions and crystal states reject without repair',()=>{const c=fixture(),good=c.getState();for(const mutate of [s=>s.combat.handIds.push(s.combat.handIds[0]),s=>s.activeCardIds.push(s.combat.temporaryCardIds[0]),s=>delete s.combat.temporaryCardMeta[s.combat.temporaryCardIds[0]],s=>s.combat.enemyState.bossMechanic.crystalsRemaining=-1,s=>s.combat.enemyState.hp=0,s=>s.combat.temporaryCardMeta[s.combat.temporaryCardIds[0]].battleId='wrong']){const s=structuredClone(good);mutate(s);assert.throws(()=>validateRunState(s,snowLanguage));}});
