import test from 'node:test';import assert from 'node:assert/strict';
import {act,newSnow,snowLanguage} from './helpers/snow-state.js';import {advanceAssigned,assignedAttack} from './helpers/desert-state.js';
import {eligibleRewardCards,createRewardOffer} from '../src/game/rewards.js';import {createShop} from '../src/game/shop.js';
import {createFrostSupply,ensureFrostVisibility,cleanupFrost} from '../src/game/frostCards.js';import {createBattlePiles} from '../src/game/deck.js';
import {RunController as Legacy051} from './helpers/legacy-051-controller.js';import {newProfile,validateRunState} from '../src/services/localStore.js';
import {registryForVersion,createSentenceSnapshot} from '../src/data/language/index.js';import {analyzeSentence,snapshotFromText} from '../src/engine/grammar/index.js';
import {COMBAT_BALANCE} from '../src/data/balance.js';import {COMPARISON_FORMS} from '../src/data/language/snowLanguage.js';
test('0.6 three actual shop visits, cumulative removal, frozen inventories and one-time services',()=>{
 const c=newSnow('snow.shop');for(const [battle,price]of [[4,6],[13,8]]){advanceAssigned(c,{stopAtBattle:battle,stopStatus:'SHOP'});const s=c.getState();assert.equal(s.shop.services.REMOVE.price,price);act(c,{type:'SHOP_SERVICE',shopId:s.shop.shopId,serviceKind:'REMOVE',targetCardInstanceId:s.activeCardIds.at(-1),confirmRemoval:true});}
 advanceAssigned(c,{stopAtBattle:22});while(c.getState().status==='BATTLE')assignedAttack(c,'I had played games and she will have played music');act(c,{type:'SKIP_REWARD',offerId:c.getState().reward.offerId});assert.equal(c.getState().status,'STAGE_CLEAR');assert.ok(c.getState().eligibility.runOwnUnlocks.includes('pack.comparison'));act(c,{type:'NEXT_STAGE'});act(c,{type:'ENTER_STAGE'});
 const s=c.getState(),rng=structuredClone(s.rng);assert.equal(s.shop.inventory.length,5);assert.equal(s.shop.inventory.filter(x=>x.kind==='RUNE').length,2);assert.equal(s.shop.services.REMOVE.price,10);assert.equal(s.shopHistory.length,2);assert.deepEqual(createShop(s),c.getState().shop);assert.deepEqual(s.rng,rng);assert.equal(validateRunState(s,snowLanguage),true);
 act(c,{type:'SHOP_SERVICE',shopId:s.shop.shopId,serviceKind:'POLISH',targetCardInstanceId:s.activeCardIds.at(-1)});assert.equal(c.dispatch({type:'SHOP_SERVICE',shopId:s.shop.shopId,serviceKind:'POLISH',targetCardInstanceId:s.activeCardIds.at(-1)}).ok,false);assert.equal(validateRunState(c.getState(),snowLanguage),true);
 act(c,{type:'LEAVE_SHOP',shopId:s.shop.shopId});assert.deepEqual(c.getState().rng.shop,rng.shop);assert.equal(c.getState().progress.battleNumber,23);
});
test('0.6 snow word rarity and actual reward/shop eligibility require reward pack',()=>{const c=newSnow(),s=c.getState(),words=['than','as','more','most','too','enough','twice'];assert.ok(words.every(w=>!eligibleRewardCards(s).some(d=>d.id==='card.'+w)));s.eligibility.runStartUnlockBaseline.push('pack.snowWords.reward');for(const w of words){const d=eligibleRewardCards(s).find(d=>d.id==='card.'+w);assert.equal(d.starterEligible,false);assert.equal(d.rarity,w==='twice'?'RARE':['more','most','enough'].includes(w)?'UNCOMMON':'COMMON');}assert.equal(s.activeCardIds.length,28);});
test('0.6 all reviewed morphology IDs preserve original forms and restrict non-degree adverbs',()=>{const old=registryForVersion('0.5.1');for(const lex of old.lexemes.filter(l=>['ADJECTIVE','ADVERB'].includes(l.pos))){const now=snowLanguage.lexemeById[lex.id];assert.ok(['INFLECTED','PERIPHRASTIC','IRREGULAR','BOTH'].includes(now.comparisonPolicy.strategy));for(const id of lex.formIds){assert.equal(snowLanguage.formById[id].surface,old.formById[id].surface);assert.equal(snowLanguage.formById[id].grammaticalFeatures.degree,'POSITIVE');}if(COMPARISON_FORMS[lex.lemma])assert.deepEqual(now.formIds.slice(-2).map(id=>snowLanguage.formById[id].surface),COMPARISON_FORMS[lex.lemma]);else assert.deepEqual(now.formIds,lex.formIds);}assert.ok(!snowLanguage.forms.some(f=>f.surface==='beautifuller'||f.surface==='quicklier'));});
test('0.6 well comparative remains the same physical adverb, superlative adverbs work',()=>{for(const text of ['She runs fastest.','She runs the fastest.','She runs most carefully.','She runs the most carefully.','She runs faster than I run.']){const a=analyzeSentence(snapshotFromText(text,{registry:snowLanguage}),snowLanguage);assert.equal(a.status,'VALID',text);}const snapshot=snapshotFromText('She runs better than me.',{registry:snowLanguage}),token=snapshot.orderedTokens[2];Object.assign(token,{lexemeId:'lex.well.adverb',cardDefId:'card.well',selectionId:'form.well.comparative',allowedFormCandidates:['form.well.comparative']});assert.equal(analyzeSentence(snapshot,snowLanguage).status,'VALID');});
test('0.6 frost fallback, separate RNG streams, same-run replay and clipped draw policy',()=>{const c=newSnow('snow.fallback'),s=c.getState();s.progress={stageId:'stage.06',roundIndex:4,battleNumber:27};for(const id of s.activeCardIds)s.cardInstances[id].cardDefId='card.book';const before=structuredClone(s.rng),a=structuredClone(s),b=structuredClone(s);const sa=createFrostSupply(a),sb=createFrostSupply(b);assert.deepEqual(sa,sb);assert.deepEqual(a.rng,before);assert.equal(sa.temporaryCardIds.length,9);const good=sa.temporaryCardIds.at(-1);assert.equal(sa.temporaryCardMeta[good].supportOnly,true);assert.equal(sa.temporaryCardMeta[good].crystalBearing,false);
 const piles=run=>{const p=createBattlePiles({activeCardIds:[...run.activeCardIds,...sa.temporaryCardIds],cardInstances:run.cardInstances,stream:run.rng.deck,registry:snowLanguage});ensureFrostVisibility(p,structuredClone(sa),COMBAT_BALANCE,true);return p;};assert.deepEqual(piles(a),piles(b));assert.deepEqual(a.rng,b.rng);assert.deepEqual(a.rng.shop,before.shop);assert.deepEqual(a.rng.reward,before.reward);
});
test('0.6 old051 actual controller boundary remains 22 without snow',()=>{const c=new Legacy051({profile:{...newProfile('old051'),guidedTutorialCompletedVersion:'0.2.1'}});act(c,{type:'NEW_RUN',config:{seed:'old.end'}});const result=advanceAssigned(c);assert.equal(result.state.status,'CONTENT_COMPLETE');assert.equal(result.state.progress.contentBoundary,'STAGE5_END');assert.equal(result.state.progress.battleNumber,22);assert.equal(c.dispatch({type:'NEXT_STAGE'}).ok,false);});
