import test from 'node:test';import assert from 'node:assert/strict';import fs from 'node:fs';
import {registryForVersion} from '../src/data/language/index.js';import {snapshotFromText,analyzeSentence} from '../src/engine/grammar/index.js';import {resolveAttack,resolveEncounter} from '../src/engine/stage.js';import {STAGE7,EMBER_PACKS} from '../src/data/stage7.js';import {getEncounter} from '../src/data/stages.js';import {comboEligibility} from '../src/engine/comboEligibility.js';
const read=name=>JSON.parse(fs.readFileSync(new URL(`./fixtures/v07/${name}`,import.meta.url),'utf8')),r=registryForVersion('0.7.0');
const packs=[...EMBER_PACKS,'pack.svoc.basic','pack.infinitive','pack.gerund','pack.svoo','pack.time.past','pack.time.perfect','pack.time.progressive','pack.time.futureWill','pack.clauseLink','pack.comparison','pack.degree'];
export function input(text,unlocks=packs,boss=false){const sentenceSnapshot=snapshotFromText(text,{registry:r}),analysis=analyzeSentence(sentenceSnapshot,r);return {analysis,sentenceSnapshot,cards:sentenceSnapshot.orderedTokens.map(t=>({instanceId:t.cardInstanceId,cardDefId:t.cardDefId,polishLevel:0})),enemy:getEncounter('stage.07',boss?4:0,'0.7.0'),stage:STAGE7,policyVersion:'0.7.0',attackId:'test.ember',comboEligibility:{version:'0.7.0',unlocks}};}
for(const c of read('07_Score_Cases_0.7.json').cases)test(`0.7 scoring ${c.id}: ${c.sentence}`,()=>{const result=resolveAttack(input(c.sentence));assert.equal(result.status,'VALID');assert.equal(result.finalPower,c.expectedPower,JSON.stringify(result.scoreTimeline.map(e=>[e.sourceId,e.after])));assert.equal(result.scoreTimeline.filter(e=>e.sourceId==='VOICE.PASSIVE').length,c.requiredTags.includes('VOICE.PASSIVE')?1:0);assert.ok(result.scoreTimeline.every(e=>Number.isSafeInteger(e.after)));});
test('0.7 grammar correctness and scale release do not depend on unlocks',()=>{const i=input('Food is eaten.',[],true),result=resolveAttack(i);assert.equal(result.status,'VALID');assert.equal(result.bossStateAfter.active,false);assert.equal(result.finalPower,result.preBossScore);assert.ok(!result.scoreTimeline.some(e=>e.sourceId==='VOICE.PASSIVE'||e.phase==='REGION'));const own=comboEligibility({version:'0.7.0',eligibility:{runStartUnlockBaseline:EMBER_PACKS,runOwnUnlocks:[]}});assert.ok(own.unlocks.includes('pack.passive'));});
test('0.7 region once, passive once, no duplicate participle modifier/gerund',()=>{const oc=resolveAttack(input('I see him running.'));assert.ok(!oc.scoreTimeline.some(e=>['MODIFIER.ADJECTIVE','CLAUSE.GERUND'].includes(e.sourceId)));const both=resolveAttack(input('The food made today is eaten because I am happy.'));assert.equal(both.scoreTimeline.filter(e=>e.phase==='REGION').length,1);assert.equal(both.scoreTimeline.filter(e=>e.sourceId==='VOICE.PASSIVE').length,1);});
for(const c of read('06_Boss_Cases_0.7.json').arithmetic)test(`0.7 assigned boss arithmetic ${c.id}`,()=>{
 const i=input(c.input.hasQualifiedIngOrPPUse?'I am eating food.':'I make food.',[],true);i.enemy.hp=c.input.hp;i.enemy.bossMechanic.active=c.input.shieldActive;if(!c.input.shieldActive){i.enemy.bossMechanic.releasedAttackId='earlier';i.enemy.bossMechanic.releaseEvidence=structuredClone(input('I am eating food.').analysis.formUses);}
 const out=resolveEncounter(i.analysis,c.input.preBossPower,i.enemy,{stage:STAGE7,attackId:i.attackId,submittedCards:i.cards});
 const actual={releasedThisAttack:c.input.shieldActive&&!out.bossStateAfter.active,shieldActiveAfter:out.bossStateAfter.active,finalPower:out.finalPower,actualHpLoss:out.actualHpLoss,hpAfter:out.enemyHpAfter,overkill:out.overkill,killed:out.killed};assert.deepEqual(actual,c.expected);
});
test('0.7 scale accepts only locally valid physical verb form evidence',()=>{
 for(const [text,releases]of [['I made food.',false],['I like interesting books.',false],['I am gone.',true],['I enjoy reading books.',true],['I have made food.',true],['Food is eat.',false],['Food be eaten.',false],['I be eating food because she is running.',true]]){const i=input(text,[],true),out=resolveAttack(i);assert.equal(out.bossStateAfter?.active,!releases,text);if(releases)assert.equal(out.finalPower,out.preBossScore);}
});
