import test from 'node:test';import assert from 'node:assert/strict';import fs from 'node:fs';
import {assignedEmber,checked,assignPiles,grantOperation,use} from './helpers/ember-state.js';
import {registryForVersion} from '../src/data/language/index.js';import {snapshotFromText,analyzeSentence} from '../src/engine/grammar/index.js';import {RunController} from '../src/game/runController.js';import {validateRunState} from '../src/services/localStore.js';
import {resolveAttack} from '../src/engine/stage.js';import {STAGE7,EMBER_PACKS} from '../src/data/stage7.js';import {getEncounter} from '../src/data/stages.js';import {cleanupDust} from '../src/game/emberDust.js';
const registry=registryForVersion('0.7.0'),read=name=>JSON.parse(fs.readFileSync(new URL('./fixtures/v07/'+name,import.meta.url),'utf8'));
test('0.7 unknown version and mismatched manifest restore reject without mutating current run',()=>{
 const c=assignedEmber(),before=c.getState();for(const mutate of [s=>s.version='0.8.0',s=>s.contentManifest.id='campaign.unknown',s=>s.contentManifest.stageIds.push('stage.08')]){const bad=structuredClone(before);mutate(bad);assert.equal(c.restoreRun(bad).ok,false);assert.deepEqual(c.getState(),before);}assert.equal(validateRunState(before,registry),true);
});
function assignSentence(c,text){const s=c.getState(),tokens=snapshotFromText(text,{registry}).orderedTokens,ids=tokens.map((t,i)=>'assigned.word.'+s.activeCardIds.length+'.'+i);tokens.forEach((t,i)=>{s.cardInstances[ids[i]]={instanceId:ids[i],cardDefId:t.cardDefId,polishLevel:0,specialEffectId:null};s.activeCardIds.push(ids[i]);});c._state=s;assignPiles(c,{hand:ids});for(let i=0;i<ids.length;i++){checked(c,{type:'ADD_CARD',cardId:ids[i]});checked(c,{type:'SET_FORM',cardId:ids[i],formId:tokens[i].selectionId});}}
for(const c of read('06_Boss_Cases_0.7.json').roleCases)test(`0.7 boss role ${c.id} ${c.sentence}`,()=>{const snapshot=snapshotFromText(c.sentence,{registry}),analysis=analyzeSentence(snapshot,registry),cards=snapshot.orderedTokens.map(t=>({instanceId:t.cardInstanceId,cardDefId:t.cardDefId,polishLevel:0})),r=resolveAttack({analysis,cards,sentenceSnapshot:snapshot,enemy:getEncounter('stage.07',4,'0.7.0'),stage:STAGE7,policyVersion:'0.7.0'});assert.equal(r.bossStateAfter?.active===false,c.qualified);});
test('0.7 runtime review covers all 36 verbs, preserves forms, and registers individual complement/passive bindings',()=>{
 const audit=read('03_Verb_Forms_Audit_0.7.json').verbs,old=registryForVersion('0.6.1');assert.equal(audit.length,36);assert.deepEqual(registry.lexemes.filter(l=>l.pos==='VERB'||l.lemma==='will').map(l=>l.lemma).sort(),audit.map(v=>v.lemma).sort());assert.deepEqual(registry.forms,old.forms);assert.deepEqual(registry.cards,old.cards);
 for(const v of audit){const l=registry.lexemeById[registry.cardById[v.cardDefId].lexemeId],bindings=l.senseIds.flatMap(id=>registry.senseById[id].frameBindings);for(const kind of v.targetObjectComplements)assert.ok(bindings.some(b=>b.frameId==='frame.svoc.'+({AP:'adj',NP:'np',NP_LEGACY:'np',BARE:'bare',TO:'to',ING:'ing',PP:'pp'}[kind])),v.lemma+':'+kind);if(!v.passivizableSourcePatterns.length)assert.ok(bindings.every(b=>!b.passiveAlternatives?.length),v.lemma);}
});
test('0.7 release commits once, stale and duplicate commands cannot damage, release save is replay validated',()=>{
 const c=assignedEmber({round:4});assignSentence(c,'I have made food.');const before=c.getState();assert.equal(c.dispatch({type:'SUBMIT',expectedRevision:before.revision-1}).ok,false);assert.deepEqual(c.getState(),before);const r=checked(c,{type:'SUBMIT'}),id=r.resolution.attackId;assert.equal(c.getState().combat.enemyState.bossMechanic.active,false);checked(c,{type:'FINISH_PRESENTATION',attackId:id});const after=c.getState();c.dispatch({type:'FINISH_PRESENTATION',attackId:id});assert.deepEqual(c.getState(),after);validateRunState(after,registry);assert.deepEqual(new RunController({initialState:JSON.parse(JSON.stringify(after)),profile:c.getProfile()}).getState(),after);
 for(const tamper of [s=>s.combat.enemyState.bossMechanic.releasedAttackId='fake',s=>s.combat.enemyState.bossMechanic.releaseEvidence[0].formCardId='fake',s=>s.stats.history[0].preBossScore=0,s=>s.stats.history[0].sentenceSnapshot.orderedTokens[0].selectionId='form.be.pp']){const bad=structuredClone(after);tamper(bad);assert.throws(()=>validateRunState(bad,registry));}
});
test('0.7 assigned Stage6 milestone unlocks Stage7 once, entry has no shop/grant; Stage7 terminal and profile stay idempotent',()=>{
 const c=assignedEmber();const s=c.getState();cleanupDust(s);s.progress={stageId:'stage.06',roundIndex:4,battleNumber:27,contentBoundary:null};s.milestoneIds=s.milestoneIds.filter(x=>x!=='STAGE6_CLEAR');s.eligibility.runOwnUnlocks=s.eligibility.runOwnUnlocks.filter(x=>!EMBER_PACKS.includes(x));s.status='STAGE_INTRO';c._beginBattle(s);s.combat.enemyState.hp=1;s.combat.enemyState.bossMechanic.crystalsRemaining=0;s.combat.enemyState.bossMechanic.brokenCount=5;c._state=s;
 // HP/crystals are assigned boundary fixtures. Damage, milestone and reward commits are real.
 assignSentence(c,'I run.');let r=checked(c,{type:'SUBMIT'});checked(c,{type:'FINISH_PRESENTATION',attackId:r.resolution.attackId});assert.equal(c.getState().status,'REWARD');assert.ok(EMBER_PACKS.every(x=>c.getState().eligibility.runOwnUnlocks.includes(x)));checked(c,{type:'CHOOSE_REWARD',offerId:c.getState().reward.offerId,choiceId:'SKIP'});assert.equal(c.getState().status,'STAGE_CLEAR');checked(c,{type:'NEXT_STAGE'});const intro=c.getState();assert.equal(intro.progress.stageId,'stage.07');const active=[...intro.activeCardIds],shops=structuredClone(intro.shopHistory),grants=structuredClone(intro.entryGrants);checked(c,{type:'ENTER_STAGE'});assert.equal(c.getState().progress.battleNumber,28);assert.deepEqual(c.getState().activeCardIds,active);assert.deepEqual(c.getState().shopHistory,shops);assert.deepEqual(c.getState().entryGrants,grants);validateRunState(c.getState(),registry);
 const boss=assignedEmber({round:4});const op=grantOperation(boss,'recycle'),b=boss.getState();assignPiles(boss,{hand:[op],discard:[b.combat.temporaryCardIds[0]]});use(boss,op);assignSentence(boss,'I have made food.');boss._state.combat.enemyState.hp=1;r=checked(boss,{type:'SUBMIT'});checked(boss,{type:'FINISH_PRESENTATION',attackId:r.resolution.attackId});const won=boss.getState();assert.equal(won.status,'REWARD');assert.deepEqual(won.combat.temporaryCardIds,[]);assert.ok(!Object.values(won.cardInstances).some(x=>x.temporary));validateRunState(won,registry);checked(boss,{type:'CHOOSE_REWARD',offerId:won.reward.offerId,choiceId:'SKIP'});const end=boss.getState(),profile=boss.getProfile();assert.equal(end.status,'CONTENT_COMPLETE');assert.equal(end.progress.contentBoundary,'STAGE7_END');assert.equal(profile.highestCompletedStage,7);assert.equal(profile.stage7CompletedRunIds.length,1);assert.equal(profile.storyClearCount,0);validateRunState(end,registry);assert.deepEqual(new RunController({initialState:JSON.parse(JSON.stringify(end)),profile}).getState(),end);boss.dispatch({type:'FINISH_PRESENTATION',attackId:r.resolution.attackId});assert.deepEqual(boss.getProfile(),profile);assert.deepEqual(boss.getState(),end);
});
