import test from 'node:test';import assert from 'node:assert/strict';
import {assignedEmber,checked,assignPiles,grantOperation,use} from './helpers/ember-state.js';
import {RunController} from '../src/game/runController.js';import {registryForVersion} from '../src/data/language/index.js';import {validateRunState,canSaveRun} from '../src/services/localStore.js';
import {assertRunInvariants} from '../src/game/invariants.js';import {createDustSupply,limitOpeningDust} from '../src/game/emberDust.js';
import {operationSpec} from '../src/data/operationSpec.js';import {operationTargetIds} from '../src/game/operationResolution.js';import {searchCandidates,operationAvailability} from '../src/game/operations.js';import {canPolish,cardKind,campaignCards} from '../src/data/cardCatalog.js';
const language=registryForVersion('0.7.0'),validate=c=>{const s=c.getState();assertRunInvariants(s,language);assert.equal(validateRunState(s,language),true);return s;};
const noChange=(c,cmd)=>{const before=c.getState(),undo=structuredClone(c.undo);assert.equal(c.dispatch(cmd).ok,false);assert.deepEqual(c.getState(),before);assert.deepEqual(c.undo,undo);};
test('0.7 D001/D002/D003/D005/D006 supply counts, deck-only RNG and deterministic start',()=>{
 for(let round=0;round<5;round++){const c=assignedEmber({round,seed:'dust.same'}),s=validate(c),count=round===4?5:2;assert.equal(s.combat.temporaryCardIds.length,count);assert.ok(!s.combat.temporaryCardIds.some(id=>s.activeCardIds.includes(id)));assert.equal(s.combat.handIds.filter(id=>s.combat.temporaryCardIds.includes(id)).length<=1,true);assert.ok(s.combat.openingTrace.witnessSlots.every(x=>s.combat.handIds.includes(x.cardInstanceId)&&cardKind(s.cardInstances[x.cardInstanceId],s.version)==='WORD'));const c2=assignedEmber({round,seed:'dust.same'});assert.deepEqual(c2.getState().combat,s.combat);assert.deepEqual(c2.getState().rng,s.rng);noChange(c,{type:'START_BATTLE'});noChange(c,{type:'ENTER_STAGE'});const before=structuredClone(s),proposal=structuredClone(s);proposal.combat=null;for(const id of s.combat.temporaryCardIds)delete proposal.cardInstances[id];createDustSupply(proposal);assert.deepEqual(proposal.rng,before.rng);assert.deepEqual(proposal.activeCardIds,before.activeCardIds);}
});
test('0.7 D004/D007/D008 initial dust limiting is stable, witness safe, handles tiny decks and large hands',()=>{
 const supply={temporaryCardIds:['d0','d1','d2','d3','d4'],dustSupplyTrace:{openingAdjustments:[]}},piles={handIds:['w','d0','d1','d2','d3','d4'],drawIds:[],openingTrace:{witnessSlots:[{cardInstanceId:'w'}]}};limitOpeningDust(piles,supply);assert.deepEqual(piles.handIds,['w','d0']);assert.deepEqual(piles.drawIds,['d1','d2','d3','d4']);assert.equal(supply.dustSupplyTrace.openingAdjustments.length,4);
 const swap=structuredClone(supply);swap.dustSupplyTrace.openingAdjustments=[];const p={handIds:['w','d0','d1','d2'],drawIds:['d3','a','b','d4']};limitOpeningDust(p,swap);assert.deepEqual(p,{handIds:['w','d0','a','b'],drawIds:['d3','d1','d2','d4']});
 const c=assignedEmber({round:4,opening:3}),s=validate(c);assert.equal(s.combat.rulesSnapshot.handLimit,14);assert.equal(s.combat.handIds.length,10);assert.ok(s.combat.handIds.filter(id=>s.combat.temporaryCardIds.includes(id)).length<=1);
});
test('0.7 D009/D011/D012/D013 obstacle commands do not mutate state/undo/RNG',()=>{
 const c=assignedEmber(),s=c.getState(),dust=s.combat.temporaryCardIds[0],word=s.activeCardIds[0];assignPiles(c,{hand:[dust,word]});checked(c,{type:'ADD_CARD',cardId:word});for(const cmd of [{type:'ADD_CARD',cardId:dust},{type:'SWAP_CARDS',handCardId:dust,sentenceCardId:word},{type:'SET_FORM',cardId:dust,formId:'form.be.is'},{type:'USE_OPERATION',sourceCardId:dust,commandId:'illegal'}])noChange(c,cmd);validate(c);
});
test('0.7 D014/D015/D016 exchange and reshuffle retain actual dust copies',()=>{
 const c=assignedEmber(),op=grantOperation(c,'supply'),s=c.getState(),dust=s.combat.temporaryCardIds[0],word=s.activeCardIds[0];assignPiles(c,{hand:[dust,word,op]});const before=c.getState();checked(c,{type:'EXCHANGE',cardIds:[dust,word,op]});const after=validate(c);assert.equal(after.combat.turnsRemaining,before.combat.turnsRemaining);assert.equal(after.combat.exchangesRemaining,before.combat.exchangesRemaining-1);assert.ok([dust,word,op].every(id=>after.combat.discardIds.includes(id)));assert.equal(after.combat.handIds.length,3);
 assignPiles(c,{hand:[],draw:[],discard:[...after.activeCardIds,...after.combat.temporaryCardIds]});checked(c,{type:'PREPARE'});const shuffled=validate(c);assert.ok([...shuffled.combat.handIds,...shuffled.combat.drawIds].includes(dust));assert.deepEqual(shuffled.combat.discardIds,[]);
});
test('0.7 D017/D018/D019–D022 ALL includes dust; WORD/POS filters reject it',()=>{
 const c=assignedEmber(),source=grantOperation(c,'supply'),s=c.getState(),dust=s.combat.temporaryCardIds;assignPiles(c,{hand:[source],draw:[...dust,...s.activeCardIds.filter(id=>id!==source)]});const effect=use(c,source);assert.deepEqual(effect.drawnCardIds,dust);assert.equal(effect.actualDrawCount,2);
 for(const kind of ['search','nounSearch','verbSearch','adjectiveSearch','connectorSearch']){const x=assignedEmber(),src=grantOperation(x,kind),state=x.getState();assignPiles(x,{hand:[src],draw:state.combat.temporaryCardIds,discard:state.activeCardIds.filter(id=>id!==src)});const v=x.getState(),spec=operationSpec(v.cardInstances[src].cardDefId,0,'PERMANENT',v.version);assert.deepEqual(operationTargetIds(v.combat,v.cardInstances,v.version,spec),[]);assert.equal(operationAvailability(v,src).ok,false);assert.deepEqual(searchCandidates(v),[]);noChange(x,{type:'USE_OPERATION',sourceCardId:src,targetCardId:v.combat.temporaryCardIds[0],expectedRevision:v.revision,battleId:v.combat.enemyState.id,commandId:'bad.dust'});}
});
test('0.7 D023/D024 recycle selects real dust, counts it and uses only deck RNG',()=>{
 for(const level of [0,1]){const c=assignedEmber(),source=grantOperation(c,'recycle',level),s=c.getState(),targets=level?[s.combat.temporaryCardIds[0],s.activeCardIds[0]]:[s.combat.temporaryCardIds[0]];assignPiles(c,{hand:[source],discard:targets});const before=c.getState(),effect=use(c,source),after=validate(c);assert.equal(effect.actualDrawCount,1+level);assert.deepEqual([...effect.drawnCardIds].sort(),[...targets].sort());assert.ok(after.combat.exhaustedIds.includes(source));for(const stream of ['reward','shop','encounter'])assert.deepEqual(after.rng[stream],before.rng[stream]);}
});
test('0.7 D025/D026/D027 supply source moves after effect, repeats with fresh command; fullhand respects space',()=>{
 const c=assignedEmber(),source=grantOperation(c,'supply',1),s=c.getState();assignPiles(c,{hand:[source],draw:[...s.combat.temporaryCardIds,...s.activeCardIds.filter(id=>id!==source)]});const e=use(c,source);assert.ok(!e.drawnCardIds.includes(source));assert.equal(e.postUseDestination,'DISCARD');const before=c.getState();noChange(c,{type:'FINISH_OPERATION',effectId:e.effectId});noChange(c,{type:'USE_OPERATION',sourceCardId:source,commandId:e.commandId});assignPiles(c,{hand:[s.activeCardIds[0]],draw:[source],discard:[...before.activeCardIds,...before.combat.temporaryCardIds].filter(id=>![source,s.activeCardIds[0]].includes(id))});checked(c,{type:'PREPARE'});use(c,source);assert.equal(c.getState().combat.operationHistory.filter(x=>x.sourceCardId===source).length,2);
 const full=assignedEmber(),src=grantOperation(full,'supply'),v=full.getState();assignPiles(full,{hand:[src,...v.activeCardIds.filter(id=>id!==src).slice(0,9)]});assert.equal(use(full,src).actualDrawCount,1);assert.equal(validate(full).combat.handIds.length,10);
});
test('0.7 D028/D029 save/load and cancelled search leave dust positions and RNG exact',()=>{
 const c=assignedEmber({round:4}),src=grantOperation(c,'search'),s=c.getState(),[a,b,d]=s.combat.temporaryCardIds;assignPiles(c,{hand:[src,a],discard:[b]});validate(c);const before=c.getState();checked(c,{type:'OPEN_OPERATION',sourceCardId:src});checked(c,{type:'CANCEL_OPERATION'});assert.deepEqual(c.getState(),before);assert.equal(canSaveRun(before),true);const loaded=new RunController({initialState:JSON.parse(JSON.stringify(before)),profile:c.getProfile()});assert.deepEqual(loaded.getState(),before);assert.ok(loaded.getState().combat.drawIds.includes(d));
});
test('0.7 D030/D032/D033 receipts survive defeat cleanup and new run has no dust',()=>{
 const c=assignedEmber(),src=grantOperation(c,'recycle'),s=c.getState();assignPiles(c,{hand:[src],discard:[s.combat.temporaryCardIds[0]]});use(c,src);for(let i=0;i<6;i++)checked(c,{type:'PREPARE',confirmed:true});const ended=validate(c);assert.equal(ended.status,'DEFEAT');assert.ok(ended.combat.operationHistory[0].cardSnapshots[s.combat.temporaryCardIds[0]]);assert.deepEqual(ended.combat.temporaryCardIds,[]);assert.ok(!Object.values(ended.cardInstances).some(x=>x.temporary));checked(c,{type:'NEW_RUN',config:{seed:'dust.new'}});assert.ok(!Object.values(c.getState().cardInstances).some(x=>x.temporary));
});
test('0.7 D034–D039 corrupt dust snapshots reject; original remains intact',()=>{
 const c=assignedEmber({round:4}),original=c.getState(),id=original.combat.temporaryCardIds[0];
 const corruptions=[s=>s.activeCardIds.push(id),s=>{s.combat.handIds=s.combat.handIds.filter(x=>x!==id);s.combat.drawIds=s.combat.drawIds.filter(x=>x!==id);s.combat.sentenceSlots.push({cardInstanceId:id,selection:null});},s=>s.combat.exhaustedIds.push(id),s=>s.combat.shatteredTemporaryIds.push(id),s=>s.cardInstances[id].temporary.source='MIRROR_SNOWFIELD',s=>s.cardInstances[id].polishLevel=1,s=>s.cardInstances[id].formId='form.run.base',s=>s.combat.handIds.push(id,id),s=>{delete s.cardInstances[id];},s=>s.combat.dustSupplyTrace.count=4,s=>s.combat.dustSupplyTrace.battleId='battle.07.01',s=>s.combat.temporaryCardMeta[id].source='MIRROR_SNOWFIELD'];
 for(const mutation of corruptions){const bad=structuredClone(original);mutation(bad);assert.throws(()=>validateRunState(bad,language));assert.throws(()=>new RunController({initialState:bad}));}assert.deepEqual(c.getState(),original);
});
test('0.7 D042 no dust in permanent content, polish or reward',()=>{const c=assignedEmber(),s=c.getState(),dust=s.cardInstances[s.combat.temporaryCardIds[0]];assert.equal(canPolish(dust,s.version),false);assert.ok(!campaignCards(s.version).some(x=>x.cardKind==='OBSTACLE'));assert.ok(s.contentManifest.cardDefIds.every(id=>id!=='card.obstacle.blackDust'));});
