import test from 'node:test';import assert from 'node:assert/strict';
import {assignedWaterways,assignPiles,checked,grantOperation,use} from './helpers/waterways-state.js';
import {RunController} from '../src/game/runController.js';
import {newProfile,validateRunState,canSaveRun,applyProfileEvent} from '../src/services/localStore.js';
import {registryForVersion} from '../src/data/language/index.js';
import {snapshotFromText} from '../src/engine/grammar/index.js';
import {createShop} from '../src/game/shop.js';
import {operationSpec} from '../src/data/operationSpec.js';
import {operationTargetIds} from '../src/game/operationResolution.js';
import {ensureWaterwaysFrostVisibility} from '../src/game/waterwaysFrost.js';
import {maxPolish} from '../src/data/cardCatalog.js';
const language=registryForVersion('0.8.0'),valid=c=>{const s=c.getState();assert.equal(validateRunState(s,language),true);return s;};
const choose=(c,choice,extra={})=>{const s=c.getState();return {type:'CHOOSE_STAGE8_WORD',choice,offerId:s.waterwaysEntryChoice.offerId,expectedRevision:s.revision,commandId:'entry.'+s.revision,confirmNone:true,...extra};};
for(const choice of ['WHO','WHICH','NONE'])test(`0.8 E001–E007/H001–H003 entry ${choice} and exact pending/resolved save`,()=>{
 const c=assignedWaterways({entry:true}),before=valid(c);assert.equal(canSaveRun(before),true);assert.equal(before.shop.stageId,'stage.06');
 const d=new RunController({initialState:JSON.parse(JSON.stringify(before)),profile:c.getProfile()});assert.deepEqual(d.getState(),before);
 const command=choose(d,choice);checked(d,command);const after=valid(d);assert.equal(after.activeCardIds.length-before.activeCardIds.length,choice==='NONE'?0:1);assert.equal(after.economy.gold,before.economy.gold);assert.equal(after.status,'SHOP');assert.equal(after.shopHistory.length,3);assert.equal(after.shop.stageId,'stage.08');assert.equal(after.shop.inventory.filter(i=>i.kind==='RUNE').length,2);assert.equal(after.shop.inventory.filter(i=>i.kind==='CARD'&&!i.cardDefId.startsWith('card.operation.')).length,2);assert.equal(after.shop.inventory.filter(i=>i.cardDefId?.startsWith('card.operation.')).length,1);
 assert.deepEqual(after.rng.deck,before.rng.deck);assert.deepEqual(after.rng.reward,before.rng.reward);assert.deepEqual(after.rng.encounter,before.rng.encounter);
 assert.equal(d.dispatch(command).ok,false);assert.equal(d.dispatch({...command,commandId:'new-command',choice:choice==='WHO'?'WHICH':'WHO',expectedRevision:after.revision}).ok,false);assert.deepEqual(d.getState(),after);
 const saved=new RunController({initialState:JSON.parse(JSON.stringify(after)),profile:d.getProfile()});assert.deepEqual(saved.getState(),after);const proposal=structuredClone(after);assert.deepEqual(createShop(proposal),after.shop);assert.deepEqual(proposal,after);
});
test('0.8 E008–E012 optional offer, no marker warning, stale/cancel rejection, no hidden that grant',()=>{
 const c=assignedWaterways({entry:true}),s=c.getState();for(const id of [...s.activeCardIds])if(['card.who','card.which','card.that'].includes(s.cardInstances[id].cardDefId)){s.activeCardIds=s.activeCardIds.filter(x=>x!==id);delete s.cardInstances[id];}delete s.waterwaysEntryChoice;c._state=s;checked(c,{type:'ENTER_STAGE'});const before=valid(c);assert.equal(before.waterwaysEntryChoice.needsNoneConfirmation,true);assert.equal(c.dispatch(choose(c,'NONE',{confirmNone:false})).ok,false);assert.deepEqual(c.getState(),before);assert.equal(c.dispatch(choose(c,'WHO',{expectedRevision:before.revision-1})).ok,false);assert.deepEqual(c.getState(),before);assert.throws(()=>createShop(structuredClone(before)));assert.deepEqual(c.getState(),before);checked(c,choose(c,'NONE'));assert.equal(c.getState().activeCardIds.length,before.activeCardIds.length);assert.equal(c.getState().entryGrants['stage.08'].cardDefIds.length,0);
 const owned=assignedWaterways({entry:true}),o=owned.getState(),id='assigned.owned.who';o.activeCardIds.push(id);o.cardInstances[id]={instanceId:id,cardDefId:'card.who',polishLevel:0,specialEffectId:null};delete o.waterwaysEntryChoice;owned._state=o;checked(owned,{type:'ENTER_STAGE'});assert.equal(owned.getState().waterwaysEntryChoice.ownedCounts.who,1);checked(owned,choose(owned,'WHO'));assert.equal(owned.getState().entryGrants['stage.08'].cardInstanceIds.length,1);
});
test('0.8 P005/P006 profile completion preserves active baseline, 28-card starter and run-only relative combo',()=>{
 const c=assignedWaterways(),before=c.getState();const p=applyProfileEvent(c.getProfile(),{type:'STAGE8_CLEAR',version:'0.8.0',runId:'other'});c.setProfile(p);assert.deepEqual(c.getState(),before);assert.ok(p.unlocks.includes('pack.waterwaysWords.reward'));assert.ok(!p.unlocks.includes('pack.relative'));
 const n=new RunController({profile:{...p,guidedTutorialCompletedVersion:'0.2.1'}});checked(n,{type:'NEW_RUN',config:{seed:'waterways.starter'}});assert.equal(n.getState().activeCardIds.length,28);assert.ok(n.getState().activeCardIds.every(id=>!['card.who','card.which','card.where'].includes(n.getState().cardInstances[id].cardDefId)));assert.deepEqual(n.getState().eligibility.runOwnUnlocks,[]);valid(n);
});
test('0.8 F001–F003/F015/F021 only battle35 supplies two support WORDs with witness-safe visibility',()=>{
 for(let round=0;round<5;round++){const c=assignedWaterways({round}),s=valid(c);assert.equal(s.combat.temporaryCardIds?.length??0,round===2?2:0);if(round!==2)continue;assert.deepEqual(s.combat.temporaryCardIds.map(id=>s.cardInstances[id].cardDefId),['card.where','card.when']);assert.ok(s.combat.handIds.some(id=>s.combat.temporaryCardIds.includes(id)));assert.ok(s.combat.openingTrace.witnessSlots.every(w=>s.combat.handIds.includes(w.cardInstanceId)));for(const id of s.combat.temporaryCardIds){assert.equal(s.combat.temporaryCardMeta[id].crystalBearing,false);assert.equal(maxPolish(s.cardInstances[id],s.version),0);assert.ok(!s.activeCardIds.includes(id));}assert.deepEqual(new RunController({initialState:JSON.parse(JSON.stringify(s)),profile:c.getProfile()}).getState(),s);}
 const piles={handIds:['a','b'],drawIds:['where'],openingTrace:{witnessSlots:[{cardInstanceId:'a'},{cardInstanceId:'b'}]}},supply={temporaryCardIds:['where'],waterwaysFrostTrace:[]};ensureWaterwaysFrostVisibility(piles,supply);assert.deepEqual(piles.handIds,['a','b']);assert.equal(supply.waterwaysFrostTrace[0].kind,'VISIBILITY_UNAVAILABLE');
});
function frostSentence(c,text){const s=c.getState(),tokens=snapshotFromText(text,{registry:language}).orderedTokens,used=new Set(),slots=tokens.map((t,i)=>{const frost=s.combat.temporaryCardIds.find(id=>!used.has(id)&&s.cardInstances[id].cardDefId===t.cardDefId);const id=frost??`assigned.city.${s.activeCardIds.length}.${i}`;used.add(id);if(!frost){s.cardInstances[id]={instanceId:id,cardDefId:t.cardDefId,polishLevel:0,specialEffectId:null};s.activeCardIds.push(id);}return {cardInstanceId:id,selection:t.selectionId};});c._state=s;assignPiles(c,{sentence:slots});return slots;}
for(const [id,text,relative]of [['F006','This is the school where I work.',true],['F007','Where do you work?',false],['F008','I know when you will come.',false],['F009','I play when you come.',false],['F010','Where you work.',false]])test(`0.8 ${id} city frost uses actual submission and shatters`,()=>{
 const c=assignedWaterways({round:2});frostSentence(c,text);const before=c.getState(),r=checked(c,{type:'SUBMIT'});assert.equal(r.resolution.consumedTemporaryCardIds.length,1);assert.equal(r.resolution.finalPower>0,id!=='F010');assert.equal(r.resolution.scoreTimeline.some(e=>e.sourceId==='CLAUSE.RELATIVE'),relative);assert.equal(c.getState().combat.turnsRemaining,before.combat.turnsRemaining-1);checked(c,{type:'FINISH_PRESENTATION',attackId:r.resolution.attackId});const s=valid(c);assert.equal(s.combat.shatteredTemporaryIds.length,1);assert.deepEqual(new RunController({initialState:JSON.parse(JSON.stringify(s)),profile:c.getProfile()}).getState(),s);
});
test('0.8 F004/F005/F011–F014 return, exchange, search filters and technical errors retain real IDs',()=>{
 const c=assignedWaterways({round:2}),s=c.getState(),f=s.combat.temporaryCardIds[0];assignPiles(c,{hand:[f]});checked(c,{type:'ADD_CARD',cardId:f});checked(c,{type:'RETURN_CARD',cardId:f});assert.deepEqual(c.getState().combat.shatteredTemporaryIds,[]);checked(c,{type:'EXCHANGE',cardIds:[f]});assert.ok(c.getState().combat.discardIds.includes(f));valid(c);
 const x=assignedWaterways({round:2}),before=x.getState();for(const kind of ['search','connectorSearch','nounSearch']){const spec=operationSpec('card.operation.'+kind,0,'PERMANENT','0.8.0'),q=structuredClone(before);q.combat.drawIds=[...q.combat.temporaryCardIds];const ids=operationTargetIds(q.combat,q.cardInstances,q.version,spec);assert.deepEqual(ids,kind==='search'?q.combat.temporaryCardIds:kind==='connectorSearch'?[q.combat.temporaryCardIds[1]]:[]);}
 frostSentence(x,'Where do you work?');const snap=x.getState();x.analyzer=()=>({status:'ENGINE_ERROR'});assert.equal(x.dispatch({type:'SUBMIT'}).ok,false);assert.deepEqual(x.getState(),snap);
 for(const kind of ['search','supply','recycle']){const z=assignedWaterways({round:2}),op=grantOperation(z,kind),state=z.getState(),frost=state.combat.temporaryCardIds[0];assignPiles(z,{hand:[op],...(kind==='recycle'?{discard:[frost]}:{draw:[frost,...state.activeCardIds.filter(id=>id!==op),state.combat.temporaryCardIds[1]]})});const e=use(z,op,kind==='search'?frost:undefined);assert.ok(e.drawnCardIds.includes(frost));assert.ok(z.getState().combat.handIds.includes(frost));assert.deepEqual(z.getState().combat.shatteredTemporaryIds,[]);}
});
test('0.8 F016–F020 strict source/metadata/partition rejects corrupt saves and cleans defeat',()=>{
 const c=assignedWaterways({round:2}),s=valid(c),id=s.combat.temporaryCardIds[0];
 for(const mutate of [x=>x.combat.temporaryCardMeta[id].crystalBearing=true,x=>x.combat.temporaryCardMeta[id].source='MIRROR_SNOWFIELD',x=>x.combat.temporaryCardMeta[id].cardKind='OPERATION',x=>x.cardInstances[id].polishLevel=1,x=>x.activeCardIds.push(id),x=>x.combat.discardIds.push(id),x=>x.combat.shatteredTemporaryIds.push(id),x=>x.progress.roundIndex=1]){const bad=structuredClone(s);mutate(bad);assert.throws(()=>validateRunState(bad,language));}
 for(let i=0;i<6;i++)checked(c,{type:'PREPARE',confirmed:true});const end=valid(c);assert.equal(end.status,'DEFEAT');assert.equal(end.combat.temporaryCardIds.length,0);assert.ok(Object.values(end.cardInstances).every(x=>!x.temporary));
});

test('0.8 H004/H006 independent services and gift removal survive Shop4 history',()=>{
 const d=assignedWaterways({entry:true});checked(d,choose(d,'WHO'));let state=valid(d);const id=state.activeCardIds.find(id=>state.cardInstances[id].polishLevel===0),gift=state.entryGrants['stage.08'].cardInstanceIds[0],before=state.economy.gold;
 checked(d,{type:'SHOP_SERVICE',shopId:state.shop.shopId,serviceKind:'POLISH',targetCardInstanceId:id});state=valid(d);assert.equal(state.cardInstances[id].polishLevel,1);assert.equal(state.economy.gold,before-state.shop.services.POLISH.price);assert.equal(d.dispatch({type:'SHOP_SERVICE',shopId:state.shop.shopId,serviceKind:'POLISH',targetCardInstanceId:id}).ok,false);
 checked(d,{type:'SHOP_SERVICE',shopId:state.shop.shopId,serviceKind:'REMOVE',targetCardInstanceId:gift,confirmed:true,confirmRemoval:true});state=valid(d);assert.equal(state.economy.paidRemovalCount,1);assert.ok(!state.activeCardIds.includes(gift));assert.equal(d.dispatch({type:'SHOP_SERVICE',shopId:state.shop.shopId,serviceKind:'REMOVE',targetCardInstanceId:id,confirmed:true}).ok,false);assert.deepEqual(state.shopHistory.map(x=>x.stageId),['stage.02','stage.04','stage.06']);assert.deepEqual(new RunController({initialState:JSON.parse(JSON.stringify(state)),profile:d.getProfile()}).getState(),state);
});

test('0.8 H005 removal prices continue across four real shop-service transactions',()=>{
 const c=assignedWaterways({entry:true,earlierRemovals:true});checked(c,choose(c,'NONE'));let s=valid(c);assert.deepEqual(s.shopHistory.map(x=>x.services.REMOVE.price),[6,8,10]);assert.ok(s.shopHistory.every(x=>x.services.REMOVE.used));assert.equal(s.economy.paidRemovalCount,3);assert.equal(s.shop.services.REMOVE.price,12);const gold=s.economy.gold;checked(c,{type:'SHOP_SERVICE',shopId:s.shop.shopId,serviceKind:'REMOVE',targetCardInstanceId:s.activeCardIds.at(-1),confirmRemoval:true});s=valid(c);assert.equal(s.economy.paidRemovalCount,4);assert.equal(s.economy.gold,gold-12);assert.deepEqual(new RunController({initialState:s,profile:c.getProfile()}).getState(),s);
});
test('0.8 F002 owned permanent when/where cannot replace or share IDs with the two city frost cards',()=>{
 const c=assignedWaterways({round:2,ownedWords:['where','when']}),s=valid(c);assert.equal(s.combat.temporaryCardIds.length,2);for(const word of ['where','when']){const id='assigned.owned.'+word;assert.ok(s.activeCardIds.includes(id));assert.ok(!s.combat.temporaryCardIds.includes(id));assert.equal(s.cardInstances[id].temporary,undefined);assert.equal(s.combat.temporaryCardIds.filter(x=>s.cardInstances[x].cardDefId==='card.'+word).length,1);}
});
test('0.8 pending/resolved entry and exact manifest reject forged receipts and foreign battle placement',()=>{
 for(const resolved of [false,true]){const c=assignedWaterways({entry:true});if(resolved)checked(c,choose(c,'WHO'));const s=valid(c);for(const mutate of [x=>x.waterwaysEntryChoice.offerId='foreign',x=>x.waterwaysEntryChoice.choices.push('THAT'),x=>x.waterwaysEntryChoice.ownedCounts.who=-1,x=>x.progress.stageId='stage.07',x=>x.contentManifest.cardDefIds.push('card.what')]){const bad=structuredClone(s);mutate(bad);assert.throws(()=>validateRunState(bad,language));}}
});
