import {chromium,firefox,webkit,expect} from '@playwright/test';
import assert from 'node:assert/strict';import fs from 'node:fs/promises';
const out=process.env.SB_WATERWAYS_UI_OUT??'.local-validation/v08/browser';await fs.mkdir(out,{recursive:true});
const report={kind:'ASSIGNED_STATE_REAL_UI_NOT_NATURAL_CAMPAIGN',checks:[],captures:[],browsers:[],errors:[],startedAt:new Date().toISOString()};
for(const engine of (process.env.SB_WATERWAYS_ENGINE?[process.env.SB_WATERWAYS_ENGINE]:['chromium','firefox','webkit'])){
 const browser=await ({chromium,firefox,webkit}[engine]).launch({headless:true}),context=await browser.newContext({viewport:{width:1366,height:768},recordVideo:engine==='chromium'?{dir:out}:undefined}),page=await context.newPage();page.setDefaultTimeout(20000);
 const errors=[];page.on('pageerror',e=>errors.push(e.message));page.on('console',m=>{if(m.type()==='error')errors.push(m.text());});
 report.browsers.push({engine,version:browser.version()});
 const check=id=>{report.checks.push({id,engine,status:'PASS'});console.log('PASS',engine,id);};
 const capture=async id=>{const file=`ASSIGNED-${engine}-${id}.png`;await page.screenshot({path:out+'/'+file,fullPage:true});report.captures.push(file);};
 try{
 await page.goto('http://127.0.0.1:5173/',{timeout:60000});await page.locator('#start-run').waitFor();
 await page.evaluate(async()=>{
  const [f,{RunController},{renderCombat},{renderShop},{renderIntro,renderStageClear,renderResult},{playAttack,createDOMPresentation},{presentOperation},overlays,{LocalStore},{registryForVersion},{snapshotFromText},{cardKind}]=await Promise.all([import('/tests/helpers/waterways-state.js'),import('/src/game/runController.js'),import('/src/ui/combat.js'),import('/src/ui/shop.js'),import('/src/ui/progression.js'),import('/src/engine/presentation.js'),import('/src/ui/operationPresentation.js'),import('/src/ui/overlays.js'),import('/src/services/localStore.js'),import('/src/data/language/index.js'),import('/src/engine/grammar/index.js'),import('/src/data/cardCatalog.js')]);
  const store=new LocalStore({registry:registryForVersion('0.8.0')});await store.init();
  window.qa={f,store,root:document.querySelector('#app'),settings:{speed:2,effectsOff:false},events:[],async reset(round=0){this.c=f.assignedWaterways({round});this.profile=this.c.getProfile();await store.saveProfile(this.profile);this.events=[];this.show();},show(){this.view?.cleanup();const s=this.c.getState();if(s.status==='BATTLE')this.view=renderCombat(this.root,s,{command:c=>this.command(c),openOverlay:k=>this.overlay(k)});else if(s.status==='SHOP')renderShop(this.root,s,{command:c=>this.command(c),onSaves:()=>this.overlay('saves')});else if(s.status==='CONTENT_COMPLETE')renderResult(this.root,s,{onSaves:()=>this.overlay('saves')});else if(s.status==='STAGE_INTRO')renderIntro(this.root,s,{onSaves:()=>this.overlay('saves'),onStart:()=>this.command({type:'ENTER_STAGE'}),onChooseWaterways:fields=>this.command({type:'CHOOSE_STAGE8_WORD',expectedRevision:s.revision,commandId:'ui.entry.'+s.revision,...fields})});else this.root.textContent=s.status;},overlay(k){if(k==='saves')return overlays.openSaves({store,profile:this.profile,state:this.c.getState(),onLoad:s=>{this.c=new RunController({initialState:s,profile:this.profile});this.show();}});if(k==='records')return overlays.openRecords(this.c.getProfile(),this.c.getState());return overlays.openDeck(this.c.getState(),k);},async command(command){const before=this.c.getState(),r=this.c.dispatch(command);this.last=r;if(!r.ok)return r;if(r.noRender)return r;
   if(r.operationEffect){this.effect=r.operationEffect;await presentOperation(r.operationEffect,{sourceElement:[...this.root.querySelectorAll('[data-card-id]')].find(n=>n.dataset.cardId===r.operationEffect.sourceCardId),showAfter:()=>{this.show();return this.view.element;}});f.checked(this.c,{type:'FINISH_OPERATION',effectId:r.operationEffect.effectId});}
   if(r.resolution){this.resolution=r.resolution;this.view?.cleanup();this.view=renderCombat(this.root,before,{locked:true});this.view.beginPresentation();const adapter=createDOMPresentation(this.root),impact=adapter.impact,highlight=adapter.highlight;this.roleFrames=[];adapter.highlight=(...args)=>{highlight(...args);const roles=[...this.root.querySelectorAll('[data-presentation-role]')].filter(n=>n.getBoundingClientRect().width>0&&getComputedStyle(n).visibility!=='hidden').map(n=>({cardId:n.closest('[data-card-id]')?.dataset.cardId,role:n.textContent}));if(roles.length)this.roleFrames.push(roles);};adapter.impact=(...args)=>{impact(...args);this.events.push({kind:'IMPACT',hp:this.root.querySelector('[data-presentation=hp]').textContent,gate:this.root.querySelector('[data-presentation=enemy]')?.dataset.gateOpen,scale:this.root.querySelector('[data-presentation=relative-seal]')?.dataset.unlocked});};this.relativeFrames=[];const score=adapter.onScore;adapter.onScore=(...args)=>{score(...args);const labels=[...this.root.querySelectorAll('[data-relative-label]')].map(n=>({text:n.textContent,rect:{w:n.getBoundingClientRect().width,h:n.getBoundingClientRect().height},visibility:getComputedStyle(n).visibility,display:getComputedStyle(n).display,parent:n.parentElement.className}));if(labels.length)this.relativeFrames.push(labels);};this.abort=new AbortController();this.presenting=true;await playAttack(r.resolution,adapter,{...this.settings,reducedMotion:matchMedia('(prefers-reduced-motion: reduce)').matches,signal:this.abort.signal});this.presenting=false;f.checked(this.c,{type:'FINISH_PRESENTATION',attackId:r.resolution.attackId});}
   this.show();return r;},words(text,round=0,reset=true){if(reset)this.c=f.assignedWaterways({round});const s=this.c.getState(),tokens=snapshotFromText(text,{registry:registryForVersion(s.version)}).orderedTokens,used=new Set(),ids=tokens.map(t=>{const frost=s.combat.temporaryCardIds?.find(id=>!used.has(id)&&s.cardInstances[id].cardDefId===t.cardDefId),id=frost??s.activeCardIds.find(id=>!used.has(id)&&cardKind(s.cardInstances[id],s.version)==='WORD');used.add(id);if(!frost)s.cardInstances[id].cardDefId=t.cardDefId;return id;});this.c._state=s;f.assignPiles(this.c,{hand:ids});this.tokens=tokens.map((t,i)=>({id:ids[i],formId:t.selectionId}));this.events=[];this.show();return this.tokens;},op(kind,level=0){this.c=f.assignedWaterways({round:2});const source=f.grantOperation(this.c,kind,level),s=this.c.getState(),dust=s.combat.temporaryCardIds;f.assignPiles(this.c,{hand:[source],draw:kind==='recycle'?s.activeCardIds.filter(id=>id!==source):[...dust,...s.activeCardIds.filter(id=>id!==source)],discard:kind==='recycle'?dust:[]});this.source=source;this.show();},capacity(hand){this.c=f.assignedWaterways({round:4,opening:3});const s=this.c.getState();while(s.activeCardIds.length<16+hand){const id='capacity.'+s.activeCardIds.length;s.activeCardIds.push(id);s.cardInstances[id]={instanceId:id,cardDefId:'card.book',polishLevel:0,specialEffectId:null};}const board=s.activeCardIds.slice(0,16),ids=[...(s.combat.temporaryCardIds??[]),...s.activeCardIds.slice(16)].slice(0,hand);s.combat.handIds=ids;s.combat.sentenceSlots=board.map(cardInstanceId=>({cardInstanceId,selection:null}));s.combat.drawIds=[...s.activeCardIds,...(s.combat.temporaryCardIds??[])].filter(id=>!ids.includes(id)&&!board.includes(id));s.runes.orderedInstanceIds=['r1','r2','r3','r4'];s.runes.instances=Object.fromEntries(['rune.perfectSentence','rune.short','rune.longSentence','rune.discards'].map((runeId,i)=>['r'+(i+1),{instanceId:'r'+(i+1),runeId,level:1}]));this.c._state=s;this.show();}};
  await qa.reset();
 });

 const slotRoundTrip=async(label,button='저장')=>{const before=await page.evaluate(()=>qa.c.getState());await page.getByRole('button',{name:button,exact:true}).click();await page.getByRole('button',{name:'슬롯 1 저장',exact:true}).click();await page.locator('dialog [role=status]').filter({hasText:'저장했습니다'}).waitFor();await page.getByRole('button',{name:'슬롯 1 불러오기',exact:true}).click();await expect(page.locator('dialog[open]')).toHaveCount(0);assert.deepEqual(await page.evaluate(()=>qa.c.getState()),before);check(label+'_INDEXEDDB_SLOT_EXACT_RESTORE');};
 for(const choice of ['WHO','WHICH','NONE']){
  await page.evaluate(()=>{qa.c=qa.f.assignedWaterways({entry:true});qa.show();});await slotRoundTrip('PENDING_'+choice);const before=await page.evaluate(()=>qa.c.getState());await capture('entry-'+choice);await page.locator('#choose-stage8-'+choice.toLowerCase()).click();assert.equal(await page.evaluate(()=>qa.c.getState().status),'SHOP');assert.equal(await page.evaluate(()=>qa.c.getState().waterwaysEntryChoice.choice),choice);assert.equal(await page.evaluate(()=>qa.c.getState().activeCardIds.length),before.activeCardIds.length+(choice==='NONE'?0:1));await expect(page.getByRole('heading',{name:/네 번째 상점/})).toBeVisible();await slotRoundTrip('SHOP4_'+choice);await capture('shop-'+choice);check('ENTRY_'+choice+'_REAL_UI_SHOP4');
 }
 await page.evaluate(()=>{qa.c=qa.f.assignedWaterways({entry:true});const s=qa.c.getState();for(const id of [...s.activeCardIds])if(['card.who','card.which','card.that'].includes(s.cardInstances[id].cardDefId)){s.activeCardIds=s.activeCardIds.filter(x=>x!==id);delete s.cardInstances[id];}delete s.waterwaysEntryChoice;qa.c._state=s;qa.c.dispatch({type:'ENTER_STAGE'});qa.show();});const optional=await page.evaluate(()=>qa.c.getState());await page.locator('#choose-stage8-none').click();await expect(page.getByRole('heading',{name:'관계사 없이 진행할까요?'})).toBeVisible();await page.keyboard.press('Escape');assert.deepEqual(await page.evaluate(()=>qa.c.getState()),optional);await page.locator('#choose-stage8-none').click();await page.getByRole('button',{name:'그대로 진행',exact:true}).click();check('NONE_WARNING_CANCEL_AND_CONFIRM');
 const compose=async(text,round=4,reset=true)=>{const tokens=await page.evaluate(({text,round,reset})=>qa.words(text,round,reset),{text,round,reset});for(const t of tokens){await page.locator(`.hand-cards [data-card-id="${t.id}"] .card-body`).click();await page.locator(`.combat-sentence [data-card-id="${t.id}"] .form-button`).click();await page.locator(`dialog [data-form-id="${t.formId}"],dialog [data-form-aliases~="${t.formId}"]`).click();}};
 const submit=async()=>{await page.locator('#attack-submit').click();await page.waitForFunction(()=>qa.presenting===true);await page.waitForFunction(()=>qa.presenting===false,{},{timeout:60000});return page.evaluate(()=>qa.resolution);};
 const sentences=['The child who runs is happy.','The book I made is good.','This is the school where I work.','A child who runs likes a book I made.','The book which was made helps a child I like.','Where do you work?','When will you come?','Who runs?','Which book do you like?','I know where you work.','I know when you will come.','I know who runs.','I know which book you like.','A child that runs likes a book I made.'];
 for(const text of sentences){await compose(text);assert.equal(await page.locator('[data-relative-label]').count(),0);assert.equal(await page.locator('[data-presentation=score]').isVisible(),false);const hp=await page.locator('[data-presentation=hp]').innerText();await page.locator('#attack-submit').click();await page.waitForFunction(()=>qa.presenting===true);assert.equal(await page.locator('[data-presentation=hp]').innerText(),hp);assert.equal(await page.locator('[data-presentation=relative-seal]').getAttribute('data-unlocked'),'false');const relative=await page.evaluate(()=>qa.resolution.analysis.relativeClauses.length);await expect(page.locator('[data-presentation=score]')).toBeVisible();if(relative){await page.locator('[data-relative-label]').first().waitFor();await capture('roles-'+text.replace(/[^a-z]+/gi,'-'));}await page.waitForFunction(()=>qa.presenting===false,{},{timeout:60000});const r=await page.evaluate(()=>qa.resolution);assert.equal(r.status,'VALID');assert.equal(await page.evaluate(()=>qa.events.length),1);assert.equal((await page.evaluate(()=>qa.events[0])).scale,String(r.bossStateAfter.unlocked));if(text.startsWith('A child')||text.startsWith('The book which'))assert.equal(r.bossStateAfter.unlocked,true);else assert.equal(r.bossStateAfter.unlocked,false);await capture('result-'+text.replace(/[^a-z]+/gi,'-'));check('ACTUAL_FORMS_SUBMIT_'+text);}
 for(const mode of ['effectsOff','reducedMotion','cancel']){await page.emulateMedia({reducedMotion:mode==='reducedMotion'?'reduce':'no-preference'});await page.evaluate(m=>{qa.settings={speed:2,effectsOff:m==='effectsOff'};},mode);await compose('A child who runs likes a book I made.');await page.locator('#attack-submit').click();await page.waitForFunction(()=>qa.presenting===true);if(mode==='cancel')await page.evaluate(()=>qa.abort.abort());await page.waitForFunction(()=>qa.presenting===false,{},{timeout:60000});const before=await page.evaluate(()=>qa.c.getState());assert.equal(before.combat.enemyState.bossMechanic.unlocked,true);await page.evaluate(()=>qa.command({type:'FINISH_PRESENTATION',attackId:qa.resolution.attackId}));assert.deepEqual(await page.evaluate(()=>qa.c.getState()),before);check('IMPACT_'+mode+'_NO_DUPLICATE');}
 await page.emulateMedia({reducedMotion:'no-preference'});
 await page.getByRole('button',{name:'저장',exact:true}).click();await page.getByRole('button',{name:'슬롯 1 저장',exact:true}).click();await page.locator('dialog [role=status]').filter({hasText:'저장했습니다'}).waitFor();await page.keyboard.press('Escape');const saved=await page.evaluate(()=>qa.c.getState());await page.evaluate(()=>qa.command({type:'PREPARE'}));await page.getByRole('button',{name:'저장',exact:true}).click();await page.getByRole('button',{name:'슬롯 1 불러오기',exact:true}).click();await expect(page.locator('dialog[open]')).toHaveCount(0);assert.deepEqual(await page.evaluate(()=>qa.c.getState()),saved);check('UNLOCK_RECEIPT_INDEXEDDB_EXACT_RESTORE');
 await page.evaluate(()=>qa.overlay('records'));await expect(page.locator('.grammar-entry[data-grammar-tag="CLAUSE.RELATIVE.OBJECT"]')).toHaveCount(1);await capture('records');await page.keyboard.press('Escape');check('RECORDS_THREE_FIXED_GUIDES');
 await page.evaluate(()=>qa.reset(2));assert.equal(await page.locator('.frost-card').count()>=1,true);await slotRoundTrip('CITY_FROST_OPENING');await capture('city-frost-opening');check('BATTLE35_FROST_WORD_VISIBLE');

 await page.evaluate(()=>{qa.c=qa.f.assignedWaterways({round:4});qa.c._state.combat.enemyState.hp=1;qa.show();});
 for(const text of ['The child who runs is happy.','The book I made is good.']){await compose(text,4,false);const r=await submit();assert.equal(r.enemyHpAfter,1);assert.equal(r.zeroReason,'BOSS_BLOCKED');assert.equal(r.bossStateAfter.unlocked,false);}
 await slotRoundTrip('LOCKED_HP1');await capture('same-battle-two-attacks-still-locked');check('NO_CROSS_ATTACK_ACCUMULATION_AT_HP1');await compose('A child who runs likes a book I made.',4,false);const killed=await submit();assert.equal(killed.enemyHpAfter,0);assert.equal(killed.bossStateAfter.unlocked,true);assert.equal(await page.evaluate(()=>qa.events[0].gate),'true');await capture('same-sentence-unlock-kill');check('SAME_SENTENCE_UNLOCK_AND_KILL');
 await compose('This is the school where I work.',2);assert.equal(await page.locator('.combat-sentence .frost-card').count(),1);const frost=await submit();assert.equal(frost.consumedTemporaryCardIds.length,1);assert.ok(frost.analysis.relativeClauses.some(r=>r.relativeRole==='ADVERBIAL'));await capture('real-city-frost-submitted');check('CITY_FROST_REAL_FORM_RELATIVE_SUBMIT_SHATTER');
 for(const text of ['This is the day when I work.','Where do you work?','When will you come?','I know where you work.','I know when you will come.','I play when you come.']){await compose(text,2);assert.equal(await page.locator('.combat-sentence .frost-card').count(),1);const r=await submit();assert.equal(r.status,'VALID');assert.equal(r.consumedTemporaryCardIds.length,1);if(!text.startsWith('This'))assert.equal(r.analysis.relativeClauses.length,0);check('CITY_FROST_VARIANT_'+text);}
 for(const kind of ['supply','search','recycle']){await page.evaluate(k=>qa.op(k),kind);await page.locator('.operation-use').click();if(kind==='search')await page.locator('.operation-target .frost-card').first().click();await page.waitForFunction(()=>qa.c.getState().combat.operationHistory.length===1&&qa.c.getState().combat.phase==='EDIT');const after=await page.evaluate(()=>qa.c.getState());assert.ok(after.combat.handIds.some(id=>after.combat.temporaryCardIds.includes(id)));assert.equal(after.combat.shatteredTemporaryIds.length,0);check('CITY_FROST_REAL_UI_'+kind.toUpperCase());}
 for(const [width,height]of [[1024,768],[1280,800],[1366,768],[1920,1080]])for(const hand of [10,14]){
  await page.setViewportSize({width,height});await page.evaluate(n=>qa.capacity(n),hand);
  const b=await page.evaluate(()=>{const box=s=>{const r=document.querySelector(s).getBoundingClientRect();return {top:r.top,bottom:r.bottom,left:r.left,right:r.right,width:r.width,height:r.height};};return {actions:box('.combat-actions'),hand:box('.hand-cards'),board:box('.combat-sentence'),tools:box('.waterways-tools'),info:box('.enemy-info'),enemy:box('.enemy-area'),button:box('.waterways-strategy'),targets:[...document.querySelectorAll('.hand-cards .card-select,.combat-actions button')].map(n=>({width:n.getBoundingClientRect().width,height:n.getBoundingClientRect().height}))};});assert.ok(b.actions.bottom<=b.hand.top,JSON.stringify(b));assert.ok(b.board.bottom<=b.actions.top,JSON.stringify(b));assert.ok(b.info.right<=b.tools.left);assert.ok(b.info.top>=b.enemy.top&&b.info.bottom<=b.enemy.bottom+1,JSON.stringify(b));assert.ok(b.tools.bottom<=b.enemy.bottom+1,JSON.stringify(b));assert.ok(b.button.height>=44);assert.ok(b.targets.every(x=>x.width>=44&&x.height>=44),JSON.stringify(b));await capture(`${width}x${height}-hand${hand}`);check(`LAYOUT_${width}x${height}_${hand}_16_4`);
 }
 assert.deepEqual(errors,[]);check('NO_BROWSER_ERRORS');
 }catch(error){report.errors.push({engine,error:error.stack,browserErrors:errors,diagnostic:await page.evaluate(()=>({r:window.qa?.resolution,frames:window.qa?.relativeFrames,events:window.qa?.events,presenting:window.qa?.presenting})).catch(()=>null)});console.error(engine,error);await capture('FAILURE').catch(()=>{});}
 finally{const video=page.video();await context.close();if(video)await video.saveAs(out+`/ASSIGNED-${engine}-play.webm`);await browser.close();}
}
report.status=report.errors.length?'FAIL':'PASS';report.finishedAt=new Date().toISOString();await fs.writeFile(out+'/report.json',JSON.stringify(report,null,2));if(report.errors.length)process.exitCode=1;console.log(report.status,report.checks.length,'checks',report.captures.length,'captures');
