import { el, button, modal, confirmDialog, toast } from './dom.js';
import { wordCard, formMenu, bindCardDrag } from './cards.js';
import { cardModel, runeDescription } from './models.js';
import { RUNE_BY_ID } from '../data/runes.js';


export function runeView(instance,{index=0,total=1,onOrder,readonly=false,entry=false}={}){
  const rune=RUNE_BY_ID[instance.runeId];
  const node=el('div',{class:`rune-slot ${entry&&rune.scope==='AT_BATTLE_RULES_SNAPSHOT'?'utility-entry':''}`,dataset:{runeId:rune.id}});node.style.setProperty('--rune-color',rune.color);
  const body=el('div',{class:'rune-slot-head'},el('span',{class:'rune-gem',text:'◆'}),el('div',{},el('strong',{text:rune.nameKo}),el('br'),el('small',{text:`Lv.${instance.level}`})));
  node.append(body,el('div',{class:'rune-effect',text:runeDescription(rune,instance.level)}));
  if(!readonly){node.tabIndex=0;node.setAttribute('role','button');node.setAttribute('aria-label',`${rune.nameKo} 설명 및 순서 변경`);const open=()=>{let view;view=modal(`${rune.nameKo} · Lv.${instance.level}`,[el('p',{text:rune.conditionDescriptionKo}),el('p',{class:'body-copy',text:runeDescription(rune,instance.level)}),el('div',{class:'dialog-actions'},button('↑ 위로',()=>{view.close();onOrder?.(index,index-1);},'secondary',{disabled:index===0}),button('↓ 아래로',()=>{view.close();onOrder?.(index,index+1);},'secondary',{disabled:index>=total-1}))]);};node.addEventListener('click',open);node.addEventListener('keydown',e=>{if(e.key==='Enter'||e.key===' '){e.preventDefault();open();}});}
  return node;
}
export function renderCombat(root,state,{command,openOverlay,selected=new Set(),locked=false,onTutorialSkip}={}){
  const combat=state.combat,enemy=combat.enemyState,rules=combat.rulesSnapshot,harbor=state.progress.stageId==='stage.02';
  let cleanupDrag;
  for(const id of selected)if(!combat.handIds.includes(id))selected.delete(id);
  const issue=el('div',{class:'score-label',dataset:{presentation:'label'}});
  const score=el('div',{class:'score-number',dataset:{presentation:'score'},hidden:true,text:'0'});
  const scoreWrap=el('div',{class:'score-stage'},score,el('div',{},issue,el('div',{class:'score-idle',text:'단어를 모아 당신의 문장을 완성하세요.'}),el('div',{class:'score-log',dataset:{presentation:'log'}})));
  const sentence=el('div',{class:'sentence-cards combat-sentence',dataset:{cardZone:'sentence',presentation:'sentence'}});
  const hand=el('div',{class:'hand-cards',dataset:{cardZone:'hand'}});
  function doCommand(cmd){if(!locked)command(cmd);}
  function openForm(id){if(locked)return;const slot=combat.sentenceSlots.find(s=>s.cardInstanceId===id);const model=cardModel(state.cardInstances[id],slot.selection);const index=combat.sentenceSlots.indexOf(slot);formMenu(model,model.forms,formId=>doCommand({type:'SET_FORM',cardId:id,formId}),{onMoveLeft:()=>doCommand({type:'REORDER_SENTENCE',cardId:id,index:Math.max(0,index-1)}),onMoveRight:()=>doCommand({type:'REORDER_SENTENCE',cardId:id,index:Math.min(combat.sentenceSlots.length-1,index+1)}),onRemove:()=>doCommand({type:'RETURN_CARD',cardId:id}),onSwap:()=>{let swap;swap=modal('손패와 맞교환',el('div',{class:'form-choices'},combat.handIds.map(handId=>button(cardModel(state.cardInstances[handId]).surface,()=>{swap.close();doCommand({type:'SWAP_CARDS',handCardId:handId,sentenceCardId:id});},'secondary'))));}});}
  const confirmExchange=button('',()=>{if(selected.size&&!locked)doCommand({type:'EXCHANGE',cardIds:[...selected]});},'secondary',{id:'discard-selected'});
  const clearSelection=button('선택 해제',()=>{selected.clear();renderHand();},'quiet',{id:'clear-card-selection'});
  function renderHand(){hand.classList.toggle('expanded-hand',combat.handIds.length>10);hand.replaceChildren(...combat.handIds.map(id=>wordCard(cardModel(state.cardInstances[id]),{zone:'hand',selected:selected.has(id),readonly:locked,onSelect:()=>{selected.has(id)?selected.delete(id):selected.add(id);renderHand();},onActivate:()=>doCommand({type:'ADD_CARD',cardId:id})})));confirmExchange.textContent=`버리기 (${selected.size}장) · 잔여 ${combat.exchangesRemaining}회`;confirmExchange.disabled=locked||selected.size===0||combat.exchangesRemaining===0;clearSelection.disabled=locked||selected.size===0;if(!combat.handIds.length)hand.append(el('p',{class:'helper',text:'손패가 비었습니다. 준비 행동으로 다음 턴 카드를 뽑을 수 있습니다.'}));}
  sentence.append(...combat.sentenceSlots.map(slot=>wordCard(cardModel(state.cardInstances[slot.cardInstanceId],slot.selection),{zone:'sentence',readonly:locked,onActivate:id=>doCommand({type:'RETURN_CARD',cardId:id}),onForm:openForm})));if(!combat.sentenceSlots.length)sentence.append(el('div',{class:'board-placeholder'},el('p',{text:'손패를 클릭하거나 이곳으로 끌어오세요.'}),el('small',{text:`문장 ${combat.sentenceSlots.length} / ${rules.sentenceLimit}장 · 클릭해서 회수`})));renderHand();
  const status=el('aside',{class:'status-panel'},el('div',{},el('div',{class:'status-label',text:'남은 행동 턴'}),el('div',{class:'turn-count'},combat.turnsRemaining,el('small',{text:` / ${rules.turnLimit}`})),el('div',{class:'turn-pips','aria-label':`남은 턴 ${combat.turnsRemaining}`},Array.from({length:rules.turnLimit},(_,i)=>el('i',{class:i<combat.turnsRemaining?'filled':''})))),el('div',{class:'resource-row'},el('span',{text:'교환'}),el('strong',{text:`${combat.exchangesRemaining}회`})),el('div',{class:'resource-row'},el('span',{text:'재화'}),el('strong',{text:`${state.economy.gold} ◈`})),el('div',{class:'status-nav'},button('사전',()=>openOverlay('dictionary'),'quiet',{disabled:locked}),button('도감',()=>openOverlay('records'),'quiet',{disabled:locked}),button('공격 기록',()=>openOverlay('recent'),'quiet',{disabled:locked}),button('내 덱',()=>openOverlay('deck'),'quiet',{disabled:locked}),button('저장',()=>openOverlay('saves'),'quiet',{disabled:locked}),button('설정',()=>openOverlay('settings'),'quiet',{disabled:locked})));
  const runePanel=el('aside',{class:'rune-panel'},el('div',{class:'rune-title'},el('strong',{text:'장착 룬'}),el('span',{text:`${state.runes.orderedInstanceIds.length} / ${state.runes.slotLimit}`})),...state.runes.orderedInstanceIds.map((id,index)=>runeView(state.runes.instances[id],{index,total:state.runes.orderedInstanceIds.length,readonly:locked,entry:!combat.battleDirty,onOrder:(from,to)=>{const ids=[...state.runes.orderedInstanceIds];const [r]=ids.splice(from,1);ids.splice(to,0,r);doCommand({type:'REORDER_RUNES',instanceIds:ids});}})),...Array.from({length:state.runes.slotLimit-state.runes.orderedInstanceIds.length},()=>el('div',{class:'rune-slot empty',text:'◇  비어 있는 슬롯'})),el('p',{class:'rune-hint',text:'공격 룬은 위에서 아래로 발동합니다. 룬을 눌러 설명과 순서를 확인하세요.'}));
  const enemyArea=el('section',{class:'enemy-area'},el('div',{class:'enemy-avatar',dataset:{presentation:'enemy'},text:enemy.emoji||'🌱'}),el('div',{class:'enemy-info'},el('div',{class:'enemy-label',text:enemy.kind==='REGIONAL_BOSS'?'REGION BOSS':harbor?'HARBOR ENCOUNTER':'GRASSLAND ENCOUNTER'}),el('h2',{text:enemy.nameKo}),el('div',{class:'hp-track'},el('div',{class:'hp-fill',dataset:{presentation:'hp-fill'},style:`width:${enemy.hp/enemy.maxHp*100}%`})),el('div',{class:'enemy-hp',dataset:{presentation:'hp'},text:`${enemy.hp} / ${enemy.maxHp}`})),el('span',{class:'region-bonus',text:harbor?'4형식 ×1.25':'기본 문형 ×1.25'}),enemy.bossMechanic?.id==='SVOO_VEIL'&&el('span',{class:'boss-veil',dataset:{presentation:'boss-veil',active:String(enemy.bossMechanic.active)},text:enemy.bossMechanic.active?'보호 장막 · 피해 ×¼ · 4형식으로 해제':'보호 장막 해제'}));
  const shell=el('main',{class:`game-shell ${locked?'presentation-locked':''}`},el('header',{class:'game-header'},el('div',{class:'stage-path'},el('span',{class:'active',text:`STAGE ${harbor?2:1}-${state.progress.roundIndex+1}`}),el('span',{text:' / '}),el('h1',{text:harbor?'전달의 항구':'시작의 초원'})),el('span',{class:'brand-small',text:'SENTENCE BALATRO'}),button('로비',()=>openOverlay('lobby'),'quiet',{disabled:locked})),enemyArea,el('div',{class:'combat-middle'},status,el('section',{class:'sentence-area'},scoreWrap,sentence,el('div',{class:'combat-actions'},button('↶ 편집 되돌리기',()=>doCommand({type:'UNDO'}),'quiet',{disabled:locked}),button('공격 확정',()=>doCommand({type:'SUBMIT'}),'primary attack-button',{id:'attack-submit',disabled:locked||!combat.sentenceSlots.length}),button(`준비 · 다음 턴 +${rules.turnDraw}`,()=>doCommand({type:'PREPARE'}),'secondary prepare-button',{disabled:locked}))),runePanel),el('section',{class:'hand-section'},button('',()=>openOverlay('draw'),'pile-button',{disabled:locked}),el('div',{class:'hand-center'},el('div',{class:'hand-title'},el('span',{text:'나의 손패 · 체크 후 버리기'}),el('span',{text:`${combat.handIds.length} / ${rules.handLimit}장${combat.handIds.length>10?' · 옆으로 밀어 보기':''}`})),hand,el('div',{class:'exchange-row'},[confirmExchange,clearSelection])),button('',()=>openOverlay('discard'),'pile-button pile-discard',{disabled:locked})));
  shell.classList.toggle('harbor-combat',harbor);
  shell.querySelector('.pile-button').append(el('span',{text:'DRAW'}),el('strong',{text:combat.drawIds.length}),el('span',{text:'드로우 더미'}));shell.querySelector('.pile-discard').append(el('span',{text:'DISCARD'}),el('strong',{text:combat.discardIds.length}),el('span',{text:'버린 카드'}));
  root.replaceChildren(el('div',{class:'portrait-notice',text:'카드가 잘 보이도록 기기를 가로로 돌려 주세요.'}),shell);
  cleanupDrag=bindCardDrag(shell,d=>{if(d.sourceZone==='hand'&&d.targetZone==='sentence'){if(d.mode==='SWAP'&&d.targetCardId)doCommand({type:'SWAP_CARDS',handCardId:d.cardId,sentenceCardId:d.targetCardId});else doCommand({type:'ADD_CARD',cardId:d.cardId,index:d.index});}else if(d.sourceZone==='sentence'&&d.targetZone==='hand'){if(d.mode==='SWAP'&&d.targetCardId)doCommand({type:'SWAP_CARDS',sentenceCardId:d.cardId,handCardId:d.targetCardId});else doCommand({type:'RETURN_CARD',cardId:d.cardId});}else if(d.sourceZone==='sentence'&&d.targetZone==='sentence'){const from=combat.sentenceSlots.findIndex(s=>s.cardInstanceId===d.cardId);doCommand({type:'REORDER_SENTENCE',cardId:d.cardId,index:d.index-(from<d.index?1:0)});}},{enabled:()=>!locked});
  const escape=e=>{if(e.key==='Escape'&&!document.querySelector('dialog[open]')&&!locked){selected.clear();renderHand();}};window.addEventListener('keydown',escape);
  return{cleanup(){cleanupDrag();window.removeEventListener('keydown',escape);},beginPresentation(){score.hidden=false;shell.querySelector('.score-idle')?.remove();},showAnalysis(analysis){issue.textContent=analysis.messageKo||'문장을 확인하세요.';shell.querySelector('.score-idle')?.remove();for(const id of analysis.issues?.flatMap(i=>i.cardIds||[])||[]){[...shell.querySelectorAll('[data-card-id]')].find(n=>n.dataset.cardId===id)?.classList.add('presentation-highlight');}},element:shell};
}
