import {TURN_HAND_SEAL_HINT} from '../data/stage5.js';
import {isTurnSealed} from '../game/turnHandSeal.js';
import {SKY_SHIELD_HINT} from '../data/stage4.js';
import {operationAvailability} from '../game/operations.js';
import {runeView,bindRuneDrag} from './runes.js';
export {runeView} from './runes.js';
import {stageForRun} from '../data/stages.js';
import {TIME_GOLEM_HINT} from '../data/stage3.js';
import { el, button, modal, confirmDialog, toast } from './dom.js';
import { wordCard, formMenu, bindCardDrag } from './cards.js';
import { cardModel, runeDescription } from './models.js';
import {isGuided,tutorialCommand,guidedAllowed} from '../game/guidedTutorial.js';
import { RUNE_BY_ID } from '../data/runes.js';


const displayedSealKeys=new WeakMap();

export function renderCombat(root,state,{command,openOverlay,selected=new Set(),locked=false,onTutorialSkip}={}){
  const combat=state.combat,enemy=combat.enemyState,rules=combat.rulesSnapshot,harbor=state.progress.stageId==='stage.02',canyon=state.progress.stageId==='stage.03',sky=state.progress.stageId==='stage.04',desert=state.progress.stageId==='stage.05',stage=stageForRun(state);
  locked=locked||combat.phase==='OPERATION_PRESENTING';
  const guided=isGuided(state);if(guided)selected=new Set(state.tutorialSession.selectedIds);
  let cleanupDrag;
  for(const id of selected)if(!combat.handIds.includes(id))selected.delete(id);
  const issue=el('div',{class:'score-label',dataset:{presentation:'label'}});
  const score=el('div',{class:'score-number',dataset:{presentation:'score'},hidden:true,text:'0'});
  const scoreWrap=el('div',{class:'score-stage'},score,el('div',{},issue,el('div',{class:'score-idle',text:'단어를 모아 당신의 문장을 완성하세요.'}),el('div',{class:'score-log',dataset:{presentation:'log'}})));
  const sentence=el('div',{class:'sentence-cards combat-sentence',dataset:{cardZone:'sentence',presentation:'sentence'}});
  const hand=el('div',{class:'hand-cards',dataset:{cardZone:'hand'}});
  function doCommand(cmd){if(!locked)return command(tutorialCommand(state,cmd));}
  async function openForm(id){if(locked)return;if(guided){const r=await doCommand({type:'TUTORIAL_FORM_OPEN',cardId:id});if(!r?.ok)return;}const slot=combat.sentenceSlots.find(s=>s.cardInstanceId===id);const model=cardModel(state.cardInstances[id],slot.selection,state.version);const index=combat.sentenceSlots.indexOf(slot);formMenu(model,model.forms,formId=>command({type:'SET_FORM',cardId:id,formId}),{onMoveLeft:()=>doCommand({type:'REORDER_SENTENCE',cardId:id,index:Math.max(0,index-1)}),onMoveRight:()=>doCommand({type:'REORDER_SENTENCE',cardId:id,index:Math.min(combat.sentenceSlots.length-1,index+1)}),onRemove:()=>doCommand({type:'RETURN_CARD',cardId:id}),onSwap:()=>{let swap;swap=modal('손패와 맞교환',el('div',{class:'form-choices'},combat.handIds.filter(handId=>cardModel(state.cardInstances[handId],null,state.version).cardKind==='WORD').map(handId=>button(cardModel(state.cardInstances[handId],null,state.version).surface,()=>{swap.close();doCommand({type:'SWAP_CARDS',handCardId:handId,sentenceCardId:id});},'secondary'))));}});}
  async function useCard(id){
    if(locked||guided)return;const model=cardModel(state.cardInstances[id],null,state.version);
    const request={type:'USE_OPERATION',sourceCardId:id,expectedRevision:state.revision,battleId:enemy.id};
    if(model.definition.operationType==='SUPPLY'){await doCommand(request);return;}
    const opened=await doCommand({type:'OPEN_OPERATION',sourceCardId:id});if(!opened?.ok)return;
    let view,confirmed=false;view=modal('탐색 · 드로우 단어 선택',[el('p',{text:'단어 이름순입니다. 드로우 순서는 표시하지 않습니다. 취소하면 카드를 사용하지 않습니다.'}),el('div',{class:'operation-target-list'},opened.candidates.map(candidate=>button(candidate.name+' · 연마 +'+candidate.polishLevel,async()=>{const result=await doCommand({...request,...opened.operationRequest,targetCardId:candidate.cardInstanceId});if(result?.ok){confirmed=true;view.close();}},'secondary operation-target',{dataset:{targetId:candidate.cardInstanceId}}))),button('탐색 취소',()=>view.close(),'quiet')],{onClose:()=>{if(!confirmed)doCommand({type:'CANCEL_OPERATION'});}});
  }
  const confirmExchange=button('',()=>{if(selected.size&&!locked)doCommand({type:'EXCHANGE',cardIds:[...selected]});},'secondary',{id:'discard-selected'});
  const clearSelection=button('선택 해제',()=>{selected.clear();renderHand();},'quiet',{id:'clear-card-selection'});
  function renderHand(){hand.classList.toggle('expanded-hand',combat.handIds.length>10);hand.replaceChildren(...combat.handIds.map(id=>wordCard(cardModel(state.cardInstances[id],null,state.version),{zone:'hand',sealed:isTurnSealed(state,id),selected:selected.has(id),readonly:locked,onSelect:()=>{if(guided){doCommand({type:'TUTORIAL_SELECT',cardId:id});return;}selected.has(id)?selected.delete(id):selected.add(id);renderHand();},onActivate:()=>doCommand({type:'ADD_CARD',cardId:id}),onUse:()=>useCard(id),useDisabled:!operationAvailability(state,id).ok,useCount:operationAvailability(state,id).actualDrawCount})));confirmExchange.textContent=`버리기 (${selected.size}장) · 잔여 ${combat.exchangesRemaining}회`;confirmExchange.disabled=locked||selected.size===0||combat.exchangesRemaining===0;clearSelection.disabled=locked||guided||selected.size===0;if(!combat.handIds.length)hand.append(el('p',{class:'helper',text:'손패가 비었습니다. 준비 행동으로 다음 턴 카드를 뽑을 수 있습니다.'}));}
  sentence.append(...combat.sentenceSlots.map(slot=>wordCard(cardModel(state.cardInstances[slot.cardInstanceId],slot.selection,state.version),{zone:'sentence',readonly:locked,onActivate:id=>doCommand({type:'RETURN_CARD',cardId:id}),onForm:openForm})));if(!combat.sentenceSlots.length)sentence.append(el('div',{class:'board-placeholder'},el('p',{text:'손패를 클릭하거나 이곳으로 끌어오세요.'}),el('small',{text:`문장 ${combat.sentenceSlots.length} / ${rules.sentenceLimit}장 · 클릭해서 회수`})));renderHand();
  const status=el('aside',{class:'status-panel'},el('div',{},el('div',{class:'status-label',text:'남은 행동 턴'}),el('div',{class:'turn-count'},combat.turnsRemaining,el('small',{text:` / ${rules.turnLimit}`})),el('div',{class:'turn-pips','aria-label':`남은 턴 ${combat.turnsRemaining}`},Array.from({length:rules.turnLimit},(_,i)=>el('i',{class:i<combat.turnsRemaining?'filled':''})))),el('div',{class:'resource-row'},el('span',{text:'교환'}),el('strong',{text:`${combat.exchangesRemaining}회`})),el('div',{class:'resource-row'},el('span',{text:'재화'}),el('strong',{text:`${state.economy.gold} ◈`})),el('div',{class:'status-nav'},button('사전',()=>openOverlay('dictionary'),'quiet',{disabled:locked,dataset:{overlay:'dictionary'}}),button('도감',()=>openOverlay('records'),'quiet',{disabled:locked}),button('공격 기록',()=>openOverlay('recent'),'quiet',{disabled:locked}),button('내 덱',()=>openOverlay('deck'),'quiet',{disabled:locked,dataset:{overlay:'deck'}}),['0.4.0','0.5.0','0.5.1'].includes(state.version)&&button('사용 완료 '+(combat.exhaustedIds?.length??0),()=>openOverlay('exhausted'),'quiet',{disabled:locked,dataset:{overlay:'exhausted'}}),button('저장',()=>openOverlay('saves'),'quiet',{disabled:locked}),button('설정',()=>openOverlay('settings'),'quiet',{disabled:locked})));
  const runePanel=el('aside',{class:'rune-panel'},el('div',{class:'rune-title'},el('strong',{text:'장착 룬'}),el('span',{text:`${state.runes.orderedInstanceIds.length} / ${state.runes.slotLimit}`})),...state.runes.orderedInstanceIds.map((id,index)=>runeView(state.runes.instances[id],{index,total:state.runes.orderedInstanceIds.length,readonly:locked||guided,version:state.version,entry:!combat.battleDirty,onOrder:(from,to)=>{const ids=[...state.runes.orderedInstanceIds];const [r]=ids.splice(from,1);ids.splice(to,0,r);doCommand({type:'REORDER_RUNES',instanceIds:ids});}})),...Array.from({length:state.runes.slotLimit-state.runes.orderedInstanceIds.length},()=>el('div',{class:'rune-slot empty',text:'◇  비어 있는 슬롯'})),el('p',{class:'rune-hint',text:'공격 룬은 위에서 아래로 발동합니다. ▲▼ 또는 손잡이로 순서를 바꾸세요.'}));
  const enemyArea=el('section',{class:'enemy-area'},el('div',{class:'enemy-avatar',dataset:{presentation:'enemy',defeated:String(enemy.hp===0)},style:enemy.hp===0?'opacity:0':null,text:enemy.emoji||'🌱'}),el('div',{class:'enemy-info'},el('div',{class:'enemy-label',text:enemy.kind==='REGIONAL_BOSS'?'REGION BOSS':desert?'WISH DESERT':sky?'SKY ISLANDS':canyon?'TIME CANYON':harbor?'HARBOR ENCOUNTER':'GRASSLAND ENCOUNTER'}),el('h2',{text:enemy.nameKo}),el('div',{class:'hp-track'},el('div',{class:'hp-fill',dataset:{presentation:'hp-fill'},style:`width:${enemy.hp/enemy.maxHp*100}%`})),el('div',{class:'enemy-hp',dataset:{presentation:'hp'},text:`${enemy.hp} / ${enemy.maxHp}`})),el('span',{class:'region-bonus',text:desert?'to · 동명사 · 5형식 ×1.25':sky?'절 연결 ×1.25':canyon?'시간 콤보 ×1.25':harbor?'4형식 ×1.25':'기본 문형 ×1.25'}),enemy.bossMechanic?.id==='SVOO_VEIL'&&el('span',{class:'boss-veil',dataset:{presentation:'boss-veil',active:String(enemy.bossMechanic.active)},text:enemy.bossMechanic.active?'보호 장막 · 피해 ×¼ · 4형식으로 해제':'보호 장막 해제'}));
  if(desert){
    enemyArea.append(el('div',{class:'canyon-tools desert-tools'},enemyArea.querySelector('.region-bonus'),el('small',{class:'canyon-focus',text:enemy.focusKo}),button('스핑크스 공략',()=>modal('소원의 스핑크스 · 이번 턴 봉인',el('p',{text:TURN_HAND_SEAL_HINT})),'quiet canyon-strategy',{disabled:locked||guided})));
    const seal=enemy.bossMechanic;
    if(seal?.id==='TURN_HAND_SEAL'&&state.status==='BATTLE'&&enemy.hp>0){
      const model=seal.sealedCardId&&state.cardInstances[seal.sealedCardId]?cardModel(state.cardInstances[seal.sealedCardId],null,state.version):null;
      enemyArea.querySelector('.enemy-info').append(el('p',{class:'boss-seal-status',role:'status','aria-live':'polite',title:TURN_HAND_SEAL_HINT,text:model?'이번 턴 봉인: '+model.surface+(combat.handIds.includes(model.id)?' · 교환 가능':' · 현재 손패 밖'):'이번 턴 봉인 대상 없음'}));
    }
    if(state.entryGrants?.['stage.05']&&state.progress.roundIndex===0&&!combat.battleDirty)issue.textContent='입장 준비: '+(state.entryGrants['stage.05'].cardDefIds.map(id=>id.slice(5)).join(' · ')||'필요 재료 보유 확인')+' · 지급은 원정당 한 번입니다.';
  }
  if(sky){enemyArea.append(el('div',{class:'canyon-tools'},enemyArea.querySelector('.region-bonus'),el('small',{class:'canyon-focus',text:enemy.focusKo}),button('문지기 공략',()=>modal('하늘길의 문지기',el('p',{text:SKY_SHIELD_HINT})),'quiet canyon-strategy',{disabled:locked||guided})));if(enemy.bossMechanic?.id==='CLAUSE_LINK_SHIELD')enemyArea.querySelector('.enemy-info').append(el('span',{class:'boss-veil sky-shield',dataset:{presentation:'boss-veil',active:String(enemy.bossMechanic.active)},text:enemy.bossMechanic.active?'연결의 보호막 · 피해 50%':'연결의 보호막 해제'}));}
  if(canyon){
    enemyArea.append(el('div',{class:'canyon-tools'},enemyArea.querySelector('.region-bonus'),el('small',{class:'canyon-focus',text:`주제: ${enemy.focusKo}`}),button('시간의 골렘 공략',()=>modal('시간의 골렘 · 세 시간 부위',el('p',{text:TIME_GOLEM_HINT})),'quiet canyon-strategy',{disabled:locked||guided})));
    if(state.entryGrants?.['stage.03']&&state.progress.roundIndex===0&&!combat.battleDirty)issue.textContent='입장 준비: '+(state.entryGrants['stage.03'].cardDefIds.map(id=>id.slice(5)).join(' · ')||'be · have · will 보유 확인')+' · 지급은 원정당 한 번입니다.';
  }
  if(enemy.bossMechanic?.id==='TIME_GOLEM'){
    const b=enemy.bossMechanic;enemyArea.append(el('div',{class:'golem-phases',dataset:{presentation:'golem-phases'}},...b.phases.map((p,i)=>el('div',{class:`golem-phase ${p.broken?'broken':i===b.activePhase?'active':'locked'}`,dataset:{phaseId:p.id,phaseIndex:String(i)}},el('strong',{class:'golem-phase-label',text:`${['🛡 과거의 갑옷','⚙ 현재의 엔진','✦ 미래의 신경'][i]} · ${p.broken?'파괴':i===b.activePhase?'활성':'잠금'}`}),el('div',{class:'hp-track'},el('div',{class:'hp-fill',style:`width:${p.hp/p.maxHp*100}%`})),el('small',{class:'golem-phase-hp',text:`${p.hp} / ${p.maxHp}`})))));
  }
  const shell=el('main',{class:`game-shell ${locked?'presentation-locked':''}`},el('header',{class:'game-header'},el('div',{class:'stage-path'},el('span',{class:'active',text:`STAGE ${Number(state.progress.stageId.slice(-2))}-${state.progress.roundIndex+1}`}),el('span',{text:' / '}),el('h1',{text:stage.nameKo})),el('span',{class:'brand-small',text:'SYNTAX ATLAS'}),button('로비',()=>openOverlay('lobby'),'quiet',{disabled:locked})),enemyArea,el('div',{class:'combat-middle'},status,el('section',{class:'sentence-area'},scoreWrap,sentence,el('div',{class:'combat-actions'},button('↶ 편집 되돌리기',()=>doCommand({type:'UNDO'}),'quiet',{disabled:locked}),button('공격 확정',()=>doCommand({type:'SUBMIT'}),'primary attack-button',{id:'attack-submit',disabled:locked||!combat.sentenceSlots.length}),button(`준비 · 다음 턴 +${rules.turnDraw}`,()=>doCommand({type:'PREPARE'}),'secondary prepare-button',{disabled:locked}))),runePanel),el('section',{class:'hand-section'},button('',()=>openOverlay('draw'),'pile-button',{disabled:locked}),el('div',{class:'hand-center'},el('div',{class:'hand-title'},el('span',{text:'나의 손패 · 체크 후 버리기'}),el('span',{text:`${combat.handIds.length} / ${rules.handLimit}장${combat.handIds.length>10?' · 옆으로 밀어 보기':''}`})),hand,el('div',{class:'exchange-row'},[confirmExchange,clearSelection])),button('',()=>openOverlay('discard'),'pile-button pile-discard',{disabled:locked})));
  shell.classList.toggle('harbor-combat',harbor);shell.classList.toggle('canyon-combat',canyon);shell.classList.toggle('sky-combat',sky);shell.classList.toggle('desert-combat',desert);
  const sealKey=enemy.bossMechanic?.id==='TURN_HAND_SEAL'&&state.status==='BATTLE'&&enemy.hp>0?enemy.bossMechanic.lastAppliedTurnKey:null;
  if(sealKey&&displayedSealKeys.get(root)!==sealKey&&!document.hidden&&!document.body.classList.contains('effects-off'))shell.classList.add('seal-arriving');
  displayedSealKeys.set(root,sealKey);
  const cleanupRunes=bindRuneDrag(runePanel,(from,to)=>{const ids=[...state.runes.orderedInstanceIds];ids.splice(to,0,...ids.splice(from,1));doCommand({type:'REORDER_RUNES',instanceIds:ids});},{enabled:()=>!locked&&!guided});
  shell.querySelector('.pile-button').append(el('span',{text:'DRAW'}),el('strong',{text:combat.drawIds.length}),el('span',{text:'드로우 더미'}));shell.querySelector('.pile-discard').append(el('span',{text:'DISCARD'}),el('strong',{text:combat.discardIds.length}),el('span',{text:'버린 카드'}));
  root.replaceChildren(el('div',{class:'portrait-notice',text:'카드가 잘 보이도록 기기를 가로로 돌려 주세요.'}),shell);
  cleanupDrag=bindCardDrag(shell,d=>{if(d.sourceZone==='hand'&&d.targetZone==='sentence'){if(d.mode==='SWAP'&&d.targetCardId)doCommand({type:'SWAP_CARDS',handCardId:d.cardId,sentenceCardId:d.targetCardId});else doCommand({type:'ADD_CARD',cardId:d.cardId,index:d.index});}else if(d.sourceZone==='sentence'&&d.targetZone==='hand'){if(d.mode==='SWAP'&&d.targetCardId)doCommand({type:'SWAP_CARDS',sentenceCardId:d.cardId,handCardId:d.targetCardId});else doCommand({type:'RETURN_CARD',cardId:d.cardId});}else if(d.sourceZone==='sentence'&&d.targetZone==='sentence'){const from=combat.sentenceSlots.findIndex(s=>s.cardInstanceId===d.cardId);doCommand({type:'REORDER_SENTENCE',cardId:d.cardId,index:d.index-(from<d.index?1:0)});}},{enabled:()=>!locked});
  const escape=e=>{if(e.key==='Escape'&&!document.querySelector('dialog[open]')&&!locked&&!guided){selected.clear();renderHand();}};window.addEventListener('keydown',escape);
  return{cleanup(){cleanupRunes();cleanupDrag();window.removeEventListener('keydown',escape);},beginPresentation(){score.hidden=false;shell.querySelector('.score-idle')?.remove();},showAnalysis(analysis){issue.textContent=analysis.messageKo||'문장을 확인하세요.';shell.querySelector('.score-idle')?.remove();for(const id of analysis.issues?.flatMap(i=>i.cardIds||[])||[]){[...shell.querySelectorAll('[data-card-id]')].find(n=>n.dataset.cardId===id)?.classList.add('presentation-highlight');}},element:shell};
}
