import { el, button, heading, toast, downloadJson } from './dom.js';
import { wordCard, formMenu, bindCardDrag, POS_LABELS } from './cards.js';
import { cardModel, runeDescription } from './models.js';
import { registry, createSentenceSnapshot } from '../data/language/index.js';
import { analyzeSentence, snapshotFromText } from '../engine/grammar/index.js';
import { resolveAttack } from '../engine/stage.js';
import { RUNES } from '../data/runes.js';
import { STAGE_BY_ID } from '../data/stages.js';
import acceptance from '../../spec/05_ACCEPTANCE_CASES_v0_1.json';

/** Isolated developer state. Never touches a run, profile, achievements, or rewards. */
export function renderSandbox(root, { onBack, presentationSample } = {}) {
  let slots=[], instances={}, serial=0, result=null, search='', category='ALL', cleanupDrag;
  let chosenRunes=[], autoAnalyze=false,stageId='stage.01';
  const fixtures=[...acceptance.grammarCases,{id:'V02_SVOO',sentenceForHumanReading:'She gives me a book',expectedStatus:'VALID'},{id:'V02_TO',sentenceForHumanReading:'She gives a book to me',expectedStatus:'VALID'},{id:'V02_FOR',sentenceForHumanReading:'She makes a game for me',expectedStatus:'VALID'}];
  const header=el('header',{class:'topbar'},button('← 로비',onBack,'quiet'),el('span',{class:'brand-small',text:'SENTENCE BALATRO'}),el('span',{class:'version-badge',text:'개발 전용 · 0.2'}));
  const catalog=el('div',{class:'catalog-grid'}), board=el('div',{class:'sentence-cards sandbox-cards',dataset:{cardZone:'sentence',presentation:'sentence'}}), output=el('div',{class:'sandbox-result'}), runeControls=el('div',{class:'sandbox-runes'}), count=el('span',{class:'counter'});
  const searchInput=el('input',{type:'search',placeholder:'단어 또는 뜻 찾기',value:search,'aria-label':'등록 카드 검색',oninput:e=>{search=e.target.value;renderCatalog();}});
  const posSelect=el('select',{'aria-label':'품사 필터',onchange:e=>{category=e.target.value;renderCatalog();}},el('option',{value:'ALL',text:'모든 품사'}),Object.entries(POS_LABELS).map(([id,label])=>el('option',{value:id,text:label})));
  const fixtureSelect=el('select',{'aria-label':'문법 테스트 사례'},el('option',{value:'',text:'문법 테스트 사례 선택…'}),fixtures.map(f=>el('option',{value:f.id,text:`${f.id} · ${f.sentenceForHumanReading} (${f.id.startsWith('V02_')?'0.2':'0.1 역사 사례'}: ${f.expectedStatus})`})));
  fixtureSelect.addEventListener('change',()=>{ const fixture=fixtures.find(f=>f.id===fixtureSelect.value); if(fixture)loadFixture(fixture); });
  const sandboxBody=el('main',{class:'sandbox-main'},heading('SENTENCE SANDBOX','문장 실험실','등록 카드로 문장을 조립하고, 같은 문법·점수 엔진의 실제 결과를 확인합니다.'),el('div',{class:'sandbox-layout'},
    el('section',{class:'panel catalog-panel'},el('div',{class:'panel-title'},el('h3',{text:'카드 레지스트리'}),el('span',{class:'muted',text:`${registry.cards.filter(c=>registry.lexemeById[c.lexemeId].runtimeReady!==false).length}종`})),el('div',{class:'filter-row'},searchInput,posSelect),catalog),
    el('section',{class:'sandbox-work'},el('div',{class:'panel'},el('div',{class:'panel-title'},el('h3',{text:'문장 조합대'}),count),el('p',{class:'helper',text:'카드 클릭으로 추가·제거 · 드래그로 순서 변경 · 형태 메뉴에서 복사'}),fixtureSelect,board,el('div',{class:'action-row'},button('분석 실행',analyze,'primary',{id:'sandbox-analyze'}),button('비우기',()=>{slots=[];instances={};changed();},'secondary'),button('입력 / 결과 JSON',()=>downloadJson('SentenceBalatro_sandbox.json',{input:snapshot(),result}),'secondary')),el('label',{class:'checkbox-row'},el('input',{type:'checkbox',onchange:e=>{autoAnalyze=e.target.checked;}}),'자동 분석 (개발 전용)')),el('div',{class:'panel'},el('h3',{text:'룬 순서 · 실험 설정'}),el('select',{'aria-label':'실험 지역',onchange:e=>{stageId=e.target.value;changed();}},el('option',{value:'stage.01',text:'시작의 초원 · 기본 문형 ×1.25'}),el('option',{value:'stage.02',text:'전달의 항구 · 4형식 ×1.25'})),runeControls),output,
    el('div',{class:'presentation-sample panel'},el('h3',{text:'연출 샘플 · 실제 판정 아님'}),el('p',{class:'muted',text:'미래 연결선 렌더러만 확인합니다. 관계절 지원·점수·플레이 기록을 생성하지 않습니다.'}),button('카드 연결선 재생',()=>{if(slots.length<2){toast('연결선을 볼 카드 두 장 이상을 추가하세요.');return;}presentationSample?.(board,slots.map(s=>s.cardInstanceId));},'secondary')))));
  root.replaceChildren(header,sandboxBody);
  function snapshot(){return createSentenceSnapshot(slots,instances,{sentenceId:'sandbox.sentence'});}
  function changed(){ result=null; renderBoard(); output.replaceChildren(el('div',{class:'panel empty-result',text:'분석 실행을 누르면 판정과 점수 기록이 여기에 표시됩니다.'})); if(autoAnalyze&&slots.length)analyze(); }
  function add(cardDefId,selection=null){ if(slots.length>=16){toast('문장 조합대는 최대 16장입니다.');return;} const id=`sandbox.card.${++serial}`;instances[id]={instanceId:id,cardDefId,polishLevel:0,specialEffectId:null};slots.push({cardInstanceId:id,selection:selection?{formId:typeof selection==='string'?selection:selection.formId}:null});changed(); }
  function remove(id){slots=slots.filter(s=>s.cardInstanceId!==id);delete instances[id];changed();}
  function move(id,index){const from=slots.findIndex(s=>s.cardInstanceId===id);const [slot]=slots.splice(from,1);slots.splice(Math.max(0,Math.min(slots.length,index)),0,slot);changed();}
  function openForm(id){const slot=slots.find(s=>s.cardInstanceId===id);const model=cardModel(instances[id],slot.selection);const index=slots.indexOf(slot);formMenu(model,model.forms,selection=>{slot.selection={formId:selection};changed();},{onMoveLeft:()=>move(id,index-1),onMoveRight:()=>move(id,index+1),onRemove:()=>remove(id),onCopy:()=>add(instances[id].cardDefId,slot.selection)});}
  function renderBoard(){cleanupDrag?.();count.textContent=`${slots.length} / 16장`;board.replaceChildren(...slots.map(s=>wordCard(cardModel(instances[s.cardInstanceId],s.selection),{zone:'sentence',onActivate:remove,onForm:openForm})));if(!slots.length)board.append(el('div',{class:'board-placeholder',text:'왼쪽에서 단어 카드를 골라 문장을 만들어 보세요.'}));cleanupDrag=bindCardDrag(board,d=>{const from=slots.findIndex(s=>s.cardInstanceId===d.cardId);move(d.cardId,d.index-(from<d.index?1:0));});}
  function renderCatalog(){ const text=search.trim().toLowerCase(); const cards=registry.cards.filter(c=>{const l=registry.lexemeById[c.lexemeId];return l.runtimeReady!==false && (category==='ALL'||l.pos===category) && (!text||`${l.lemma} ${l.glossKo}`.toLowerCase().includes(text));});catalog.replaceChildren(...cards.map(c=>{const l=registry.lexemeById[c.lexemeId];return button('',()=>add(c.id),`catalog-item pos-${l.pos}`,{'aria-label':`${l.lemma} 카드 추가`});}));[...catalog.children].forEach((node,index)=>{const l=registry.lexemeById[cards[index].lexemeId];node.append(el('strong',{text:l.lemma}),el('span',{text:`${POS_LABELS[l.pos]} · ${l.glossKo}`}));});}
  function renderRunes(){runeControls.replaceChildren(...[0,1,2].map(i=>{const sel=el('select',{'aria-label':`실험 룬 ${i+1}`,onchange:e=>{if(e.target.value&&chosenRunes.some((r,n)=>n!==i&&r?.runeId===e.target.value)){toast('같은 룬은 한 슬롯에만 장착할 수 있습니다.');renderRunes();return;}chosenRunes[i]=e.target.value?{instanceId:`sandbox.rune.${i}`,runeId:e.target.value,level:1}:null;renderRunes();changed();}},el('option',{value:'',text:`${i+1}번 슬롯 · 없음`}),RUNES.map(r=>el('option',{value:r.id,text:r.nameKo,selected:chosenRunes[i]?.runeId===r.id})));const rune=RUNES.find(r=>r.id===chosenRunes[i]?.runeId);const level=el('select',{'aria-label':`실험 룬 ${i+1} 레벨`,disabled:!rune,onchange:e=>{chosenRunes[i].level=Number(e.target.value);renderRunes();changed();}},[1,2,3].map(n=>el('option',{value:n,text:`Lv.${n}`,selected:chosenRunes[i]?.level===n})));return el('div',{class:'rune-config'},sel,level,rune&&el('small',{text:runeDescription(rune,chosenRunes[i].level)}));}));}
  function loadFixture(fixture){try{const snap=snapshotFromText(fixture.sentenceForHumanReading,{prefix:`sandbox.${fixture.id}`,sentenceId:'sandbox.sentence'});instances={};slots=snap.orderedTokens.map(t=>{instances[t.cardInstanceId]={instanceId:t.cardInstanceId,cardDefId:t.cardDefId,polishLevel:0,specialEffectId:null};return{cardInstanceId:t.cardInstanceId,selection:{formId:t.selectionId}};});serial+=slots.length;changed();toast(`${fixture.id} 입력을 불러왔습니다. 분석은 아직 실행하지 않았습니다.`);}catch(error){toast(`사례 로드 오류: ${error.message}`);}}
  function analyze(){try{const input=snapshot();const analysis=analyzeSentence(input);const cards=Object.values(instances).map(c=>({...c,baseScore:registry.cardById[c.cardDefId].baseScore}));const resolution=['VALID','VALID_WITH_ISSUES'].includes(analysis.status)?resolveAttack({attackId:`attack.sandbox.${++serial}`,analysis,cards,equippedRunes:chosenRunes.filter(Boolean),stage:STAGE_BY_ID[stageId],enemy:{hp:220,hpMax:220,stageId},sentenceSnapshot:input}):null;result={analysis,resolution};renderResult();}catch(error){result={analysis:{status:'ENGINE_ERROR',message:'판정 처리에 문제가 생겼습니다.',diagnostics:{errorId:error.message}}};renderResult();}}
  function renderResult(){const a=result.analysis,r=result.resolution;const issueText=a.issues?.map(i=>i.messageKo||i.labelKo||i.code).join(' · ');const summary=el('div',{class:'panel result-summary'},el('div',{class:'panel-title'},el('span',{class:`status-pill ${a.status}`,text:a.status}),el('strong',{text:r?`${r.finalPower} 위력`:'공격 없음'})),el('p',{text:a.messageKo||a.message||issueText||'판정 결과'}),r&&el('div',{class:'metric-row'},el('span',{text:`룬 전 ${r.preRuneScore}`}),el('span',{text:`룬 후 ${r.postRuneScore}`}),el('span',{text:`지역 후 ${r.postRegionScore}`})));
    const rows=(r?.scoreTimeline||[]).map(e=>el('tr',{},el('td',{text:e.labelKo}),el('td',{text:e.before}),el('td',{text:e.after}),el('td',{text:e.highlightCardIds.join(', ')})));
    const timeline=r&&el('div',{class:'panel overflow'},el('h3',{text:'실제 점수 타임라인'}),el('table',{},el('thead',{},el('tr',{},['이벤트','이전','이후','카드 범위'].map(s=>el('th',{text:s})))),el('tbody',{},rows)));
    const detail=el('details',{class:'panel'},el('summary',{text:'분석 구조 · Node / Hit / Issue / 카드 범위 JSON'}),el('pre',{text:JSON.stringify(a,null,2)}));output.replaceChildren(summary,...(timeline?[timeline]:[]),detail);
  }
  renderCatalog();renderRunes();changed();
  return()=>cleanupDrag?.();
}
